"""Writes the crop produce anchor table the game reads from the Blender crop reports.

    python Scripts/Blender/crop_produce_anchors.py

Each crop recipe (Scripts/Blender/Recipes/crop_*.py) records in its report.json where its produce
(SM_Crop<Name>_Produce) sits on each stage's plants: "produce": {"anchors": {"Young": [[x, y, z,
yaw, scale], ...], ...}} in Blender plot-local metres. This converts them to Unreal plot-local
centimetres (Blender +Y is Unreal -Y; yaw flips with it) and writes
Source/SurvivalGame/HomesteadCropProduceAnchors.inc, which AHomesteadWorld::BuildPlot includes.
Run it after rebuilding a crop recipe.
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
PROPS = ROOT / 'Assets' / 'Props'
OUT = ROOT / 'Source' / 'SurvivalGame' / 'HomesteadCropProduceAnchors.inc'
STAGES = ('Young', 'Growing', 'Mature', 'Ripe')  # CropStage::Young .. Ripe


def main():
    rows = []
    for report_path in sorted(PROPS.glob('Crop*/report.json')):
        report = json.loads(report_path.read_text(encoding='utf-8'))
        produce = report.get('produce')
        if not produce:
            continue
        visual = report_path.parent.name
        for stage in STAGES:
            for x, y, z, yaw, scale in produce.get('anchors', {}).get(stage, []):
                rows.append(f'{{TEXT("{visual}"), {STAGES.index(stage)}, {x * 100:.2f}f, {-y * 100:.2f}f, '
                            f'{z * 100:.2f}f, {-yaw:.1f}f, {scale:.3f}f}},')
    header = ['// Generated by Scripts/Blender/crop_produce_anchors.py from Assets/Props/Crop*/report.json;',
              '// do not edit by hand.',
              '// {crop visual, stage (0 Young, 1 Growing, 2 Mature, 3 Ripe), x, y, z (cm, plot-local), yaw (deg), scale}']
    OUT.write_text('\n'.join(header + rows) + '\n', encoding='utf-8')
    print(f'{len(rows)} anchors -> {OUT}')


if __name__ == '__main__':
    main()
