// Native tests for the cove route (Simulation/HomesteadEstateCoveRoute, generated by
// Scripts/Terrain/cove_route.py): a complete on-foot way from the manor's front door to the cove, within the
// path grade and Props' step kit, protected wherever it's steep, and clear of the river, trees and forage.
#include "../Source/SurvivalGame/Simulation/HomesteadEstate.h"
#include "../Source/SurvivalGame/Simulation/HomesteadEstateCoveRoute.h"
#include "../Source/SurvivalGame/Simulation/HomesteadCoveRouteKit.h"
#include "../Source/SurvivalGame/Simulation/HomesteadSimulation.h"

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <vector>

using namespace Homestead;

namespace
{
int Failures = 0;
void Check(bool ok, const char* what, double value = 0.0)
{
    if (!ok)
    {
        std::printf("FAIL: %s (%g)\n", what, value);
        ++Failures;
    }
}
constexpr double Pi = 3.14159265358979323846;
double Distance(Point a, Point b) { return std::hypot(a.x - b.x, a.y - b.y); }
Point Along(Point p, double yaw, double cm) { return {p.x + std::cos(yaw * Pi / 180.0) * cm, p.y + std::sin(yaw * Pi / 180.0) * cm}; }
double YawDifference(double a, double b)
{
    const double d = std::fmod(std::fabs(a - b), 360.0);
    return std::min(d, 360.0 - d);
}
double SegmentDistance(Point a, Point b, Point p)
{
    const double dx = b.x - a.x, dy = b.y - a.y, len2 = dx * dx + dy * dy;
    const double t = len2 > 0.0 ? std::clamp(((p.x - a.x) * dx + (p.y - a.y) * dy) / len2, 0.0, 1.0) : 0.0;
    return Distance(p, {a.x + t * dx, a.y + t * dy});
}
double PolylineDistance(const std::vector<Point>& line, Point p)
{
    double best = 1e300;
    for (size_t i = 0; i + 1 < line.size(); ++i) best = std::min(best, SegmentDistance(line[i], line[i + 1], p));
    return best;
}
const CoveRouteStation* NearestPathStation(const CoveRoute& route, Point p, double& distance)
{
    const CoveRouteStation* best = nullptr;
    distance = 1e300;
    for (const CoveRouteStation& s : route.stations)
    {
        if (s.onSteps) continue;
        const double d = Distance(s.position, p);
        if (d < distance)
        {
            distance = d;
            best = &s;
        }
    }
    return best;
}
}

int main()
{
    const CoveRoute& route = EstateCoveRoute();
    const EstateLayout& layout = ProvisionalEstateLayout();
    Check(route.stations.size() > 400, "centreline stations", static_cast<double>(route.stations.size()));
    Check(route.flights.size() >= 5, "flights", static_cast<double>(route.flights.size()));
    Check(route.fingerposts.size() == 2, "fingerposts", static_cast<double>(route.fingerposts.size()));
    if (route.stations.size() < 2 || route.flights.empty() || route.fingerposts.size() != 2)
    {
        std::printf("HomesteadCoveRouteTests: %d failures\n", Failures);
        return 1;
    }

    // From the manor's front door, outside the ruin, to the sand at the head of the cove.
    const Point door = EstateManorFrontDoor(layout);
    const CoveRouteStation& first = route.stations.front();
    const CoveRouteStation& last = route.stations.back();
    Check(Distance(first.position, door) < 300.0, "starts at the manor's front door", Distance(first.position, door));
    Check(!PointInPolygon(layout.FindPolygon(Anchor::ManorFootprint)->points, first.position), "starts outside the ruin");
    const Point cove = layout.PointOr(Anchor::CoveBeach, {});
    Check(Distance(last.position, cove) < 10000.0, "ends at the cove", Distance(last.position, cove));
    Check(last.walkZ > 100.0 && last.walkZ < 500.0, "ends on the sand, just above the sea", last.walkZ);
    Check(first.walkZ - last.walkZ > 8000.0, "falls the manor's 80-odd metres", first.walkZ - last.walkZ);
    Check(route.Length() > 400.0 && route.Length() < 700.0, "a walk of about half a kilometre", route.Length());

    const std::vector<Point>& boundary = layout.FindPolygon(Anchor::EstateBoundary)->points;
    for (size_t i = 0; i < route.stations.size(); ++i)
    {
        const CoveRouteStation& s = route.stations[i];
        Check(PointInPolygon(boundary, s.position), "on the estate", s.metres);
        if (i == 0) continue;
        const CoveRouteStation& p = route.stations[i - 1];
        const double run = s.metres - p.metres;
        Check(run > 0.0 && run < 1.01, "stations every metre", run);
        // No exposed slope: anything steeper than a path is on steps.
        if (run > 0.5 && std::fabs(s.walkZ - p.walkZ) / (run * 100.0) > CoveRouteMaxPathGrade + 0.01)
            Check(s.onSteps || p.onSteps, "steep only on steps", s.metres);
        // A metre of steps climbs at most 100 / 30 + 1 risers; a metre of path 1 in 7.
        const double most = (s.onSteps || p.onSteps) ? (100.0 / CoveRouteMinGoingCm + 1.0) * CoveRouteMaxRiseCm
                                                     : CoveRouteMaxPathGrade * run * 100.0 + 1.0;
        Check(std::fabs(s.walkZ - p.walkZ) <= most, "no drop between stations", s.metres);
        Check(s.bedZ <= s.walkZ + 0.01, "the ground never above the walk", s.metres);
        if (s.onSteps) Check(s.walkZ - s.bedZ >= 4.9, "the ground cut under the steps", s.metres);
    }
    // Path grades over 2 m or more (chords on its curves).
    for (size_t i = 0; i < route.stations.size(); ++i)
    {
        size_t j = i + 1;
        while (j < route.stations.size() && route.stations[j].metres - route.stations[i].metres < 2.0) ++j;
        if (j >= route.stations.size()) break;
        bool path = true;
        for (size_t k = i; k <= j; ++k) path = path && !route.stations[k].onSteps;
        if (!path) continue;
        const double grade = std::fabs(route.stations[j].walkZ - route.stations[i].walkZ)
            / ((route.stations[j].metres - route.stations[i].metres) * 100.0);
        Check(grade <= CoveRouteMaxPathGrade + 0.005, "path no steeper than 1 in 7", grade);
    }

    // Flights within Props' kit, with landings between, joined to the path or a landing at both ends.
    for (const CoveRouteFlight& f : route.flights)
    {
        Check(f.rise >= CoveRouteMinRiseCm - 0.01 && f.rise <= CoveRouteMaxRiseCm + 0.01, "rise 15-17 cm", f.rise);
        Check(f.going >= CoveRouteMinGoingCm - 0.01 && f.going <= CoveRouteMaxGoingCm + 0.01, "going 30-35 cm", f.going);
        Check(f.treads >= 3 && f.treads <= CoveRouteMaxRisers, "3-12 risers to a flight", f.treads);
        Check(f.railPitch == 26.0 || f.railPitch == 28.0 || f.railPitch == 30.0, "a standard raked rail", f.railPitch);
        Check(std::fabs(f.PitchDegrees() - f.railPitch) <= 1.0, "pitch matches its rail bay", f.PitchDegrees());
        Check(2.0 * f.rise + f.going > 59.0 && 2.0 * f.rise + f.going < 69.0, "2R + G about 64 cm", 2.0 * f.rise + f.going);
        const double footZ = f.z - f.rise;
        const double topZ = f.TreadZ(f.treads - 1);
        const Point topEdge = f.TreadPivot(f.treads);
        bool foot = false, head = false;
        for (const CoveRouteLanding& l : route.landings)
        {
            if (Distance(Along(l.position, l.yaw, l.length), f.start) < 40.0 && std::fabs(l.z - footZ) < 1.0) foot = true;
            if (Distance(l.position, topEdge) < 5.0 && std::fabs(l.z - topZ) < 1.0) head = true;
        }
        double d = 0.0;
        if (const CoveRouteStation* s = NearestPathStation(route, f.start, d); s && d < 110.0 && std::fabs(s->walkZ - footZ) < 20.0)
            foot = true;
        if (const CoveRouteStation* s = NearestPathStation(route, topEdge, d); s && d < 110.0 && std::fabs(s->walkZ - topZ) < 20.0)
            head = true;
        Check(foot, "a flight's foot meets the path or a landing", f.start.x);
        Check(head, "a flight's head meets the path or a landing", f.start.x);
        // A rail down its drop side, the flight's whole length.
        double railed = 0.0;
        const Point end = f.TreadPivot(f.treads);
        for (const CoveRouteRail& r : route.rails)
            if (r.pitch == f.railPitch && YawDifference(r.yaw, f.yaw) < 0.5 && SegmentDistance(f.start, end, r.position) < 100.0)
                railed += r.length;
        Check(railed >= 0.95 * f.treads * f.going, "every flight railed", railed);
    }
    for (const CoveRouteLanding& l : route.landings) Check(l.length >= CoveRouteMinLandingCm, "landings at least 1.2 m", l.length);
    Check(route.Steps() >= 100, "steps down the valley side", route.Steps());

    // Where she steps on and off each flight, the graded ground is the level she steps from: no pit in front
    // of the bottom riser (review, 2026-09-30: 12-17 cm, a 30 cm first step), nothing standing proud at the top.
    Check(route.flightEnds.size() == route.flights.size(), "ground sampled at every flight's ends",
          static_cast<double>(route.flightEnds.size()));
    for (size_t i = 0; i < std::min(route.flightEnds.size(), route.flights.size()); ++i)
    {
        const CoveRouteFlight& f = route.flights[i];
        const double footZ = f.z - f.rise, topZ = f.TreadZ(f.treads - 1);
        // Onto a landing, the ground lies under its slab, 4-40 cm down (only its front edge and sides show, and
        // those sit on the 25 cm block's skirt); onto a path, it's the path's own level.
        bool footLanding = false, headLanding = false;
        for (const CoveRouteLanding& l : route.landings)
        {
            footLanding = footLanding || Distance(Along(l.position, l.yaw, l.length), f.start) < 40.0;
            headLanding = headLanding || Distance(l.position, f.TreadPivot(f.treads)) < 5.0;
        }
        for (int k = 0; k < 3; ++k)
        {
            const double foot = route.flightEnds[i].foot[k] - footZ, head = route.flightEnds[i].head[k] - topZ;
            if (footLanding)
                Check(foot >= -40.0 && foot <= -4.0, "ground under the landing at a flight's foot", foot);
            else
                Check(foot >= -8.0 && foot <= 2.0, "the path's level in front of a flight's bottom riser", foot);
            if (headLanding)
                Check(head >= -40.0 && head <= -4.0, "ground under the landing at a flight's head", head);
            else
                Check(head >= -8.0 && head <= 2.0, "the path's level off a flight's top tread", head);
        }
    }

    // No path runs beside or under a flight's treads (review, 2026-09-30: the path from the bench steps' foot
    // doubled back under them): every path station stays outside each flight's footprint plus the path's
    // own clear half-width, except where it meets the flight at its foot or head.
    for (const CoveRouteStation& s : route.stations)
    {
        if (s.onSteps) continue;
        for (const CoveRouteFlight& f : route.flights)
        {
            const double a = f.yaw * Pi / 180.0;
            const double dx = s.position.x - f.start.x, dy = s.position.y - f.start.y;
            const double along = dx * std::cos(a) + dy * std::sin(a);
            const double across = -dx * std::sin(a) + dy * std::cos(a);
            const bool beside = along > 5.0 && along < f.treads * f.going - 5.0;
            Check(!beside || std::fabs(across) >= 0.5 * (CoveRouteTreadWidthCm + CoveRouteClearWidthCm),
                  "no path beside or under a flight", s.metres);
        }
    }

    // The graded heightfield itself (not just the design): the path's ground is its walking surface, level
    // across and within the grade along; under the steps it stays clear of every tread.
    Check(route.ground.size() == route.stations.size(), "graded ground sampled at every station",
          static_cast<double>(route.ground.size()));
    if (route.ground.size() == route.stations.size())
    {
        for (size_t i = 0; i < route.stations.size(); ++i)
        {
            const CoveRouteStation& s = route.stations[i];
            const CoveRouteGround& g = route.ground[i];
            Check(std::fabs(g.metres - s.metres) < 0.01, "ground samples in step with the stations", s.metres);
            if (s.onSteps)
            {
                // 1/128 m heightfield steps: at least 4 cm under the tread top on the centreline and at its edges.
                Check(std::max({g.leftZ, g.centreZ, g.rightZ}) <= s.walkZ - 4.0, "the graded ground clear of the treads", s.metres);
                continue;
            }
            // At a flight's foot or head the ground meets its riser; from 25 cm on, the path's own level holds
            // (review, 2026-09-30: a pit in front of a bottom step made a 30 cm first step).
            bool atJoin = false;
            for (const CoveRouteFlight& f : route.flights)
                atJoin = atJoin || Distance(s.position, f.start) < 25.0 || Distance(s.position, f.TreadPivot(f.treads)) < 25.0;
            if (atJoin) continue;
            Check(g.centreZ <= s.walkZ + 3.0, "the path not buried", g.centreZ - s.walkZ);
            Check(g.centreZ >= s.walkZ - 10.0, "the path not sunk", g.centreZ - s.walkZ);
            const double across = std::max(std::fabs(g.leftZ - g.centreZ), std::fabs(g.rightZ - g.centreZ));
            Check(across <= 0.25 * CoveRouteGroundSampleCm, "the path level across (1 in 4 at most)", across);
        }
        for (size_t i = 0; i < route.stations.size(); ++i)
        {
            size_t j = i + 1;
            while (j < route.stations.size() && route.stations[j].metres - route.stations[i].metres < 2.0) ++j;
            if (j >= route.stations.size()) break;
            bool path = true;
            for (size_t k = (i > 0 ? i - 1 : i); k <= std::min(j + 1, route.stations.size() - 1); ++k)
                path = path && !route.stations[k].onSteps;
            if (!path) continue;
            const double grade = std::fabs(route.ground[j].centreZ - route.ground[i].centreZ)
                / ((route.stations[j].metres - route.stations[i].metres) * 100.0);
            Check(grade <= CoveRouteMaxPathGrade + 0.02, "the graded path within 1 in 7", grade);
        }
    }

    // Kerbs and rails stand outside the 1.4 m clear width, on the path, along their whole length (review,
    // 2026-09-30: a kerb's pivot can be clear while its end reaches into the next stretch at a hairpin).
    std::vector<Point> centreline;
    for (const CoveRouteStation& s : route.stations) centreline.push_back(s.position);
    auto clearAlong = [&](Point from, double yaw, double start, double end) {
        double least = 1e300;
        for (int i = 0; i <= 10; ++i) least = std::min(least, PolylineDistance(centreline, Along(from, yaw, start + (end - start) * i / 10.0)));
        return least;
    };
    // cove_route.py CLEAR_MARGIN_M: a joint kerb on a gentle curve dips 1-2 cm inside; nothing reaches 5 cm in.
    constexpr double ClearMarginCm = 5.0;
    for (const CoveRouteKerb& k : route.kerbs)
        Check(clearAlong(k.position, k.yaw, -50.0, 50.0) >= 0.5 * CoveRouteClearWidthCm - ClearMarginCm,
              "a kerb clear of the path along its length", clearAlong(k.position, k.yaw, -50.0, 50.0));
    for (const CoveRouteRail& r : route.rails)
        if (r.pitch == 0.0)
            Check(clearAlong(r.position, r.yaw, 0.0, r.length) >= 0.5 * CoveRouteClearWidthCm - ClearMarginCm,
                  "a level rail bay clear of the path", clearAlong(r.position, r.yaw, 0.0, r.length));
    // A kerb line has no short holes: along each side of the path, kerbs follow at about 1 m, and a gap
    // under 3 m (which the generator bridges) never appears (review: dropped joint kerbs left 1 m holes).
    {
        struct Placed { double metres; int side; };
        std::vector<Placed> placed;
        // Each kerb's chainage by projection onto the nearest centreline segment (stations are 1 m apart and
        // kerbs sit between them, so snapping to a station would invent 2 m gaps).
        for (const CoveRouteKerb& k : route.kerbs)
        {
            double best = 1e300, metres = 0.0;
            int side = 1;
            for (size_t i = 0; i + 1 < route.stations.size(); ++i)
            {
                const Point a = route.stations[i].position, b = route.stations[i + 1].position;
                const double dx = b.x - a.x, dy = b.y - a.y, len2 = dx * dx + dy * dy;
                const double u = len2 > 0.0 ? std::clamp(((k.position.x - a.x) * dx + (k.position.y - a.y) * dy) / len2, 0.0, 1.0) : 0.0;
                const double d = Distance(k.position, {a.x + u * dx, a.y + u * dy});
                if (d < best)
                {
                    best = d;
                    metres = route.stations[i].metres + u * (route.stations[i + 1].metres - route.stations[i].metres);
                    side = dx * (k.position.y - a.y) - dy * (k.position.x - a.x) > 0.0 ? 1 : -1;
                }
            }
            placed.push_back({metres, side});
        }
        for (const int side : {1, -1})
        {
            std::vector<double> along;
            for (const Placed& p : placed) if (p.side == side) along.push_back(p.metres);
            std::sort(along.begin(), along.end());
            for (size_t i = 1; i < along.size(); ++i)
            {
                const double gap = along[i] - along[i - 1];
                Check(gap < 1.6 || gap >= 3.0, "no short hole in a kerb line", along[i - 1]);
            }
        }
    }
    for (const CoveRouteKerb& k : route.kerbs)
    {
        const CoveRoute::Nearest n = route.NearestTo(k.position);
        Check(n.distanceCm > 0.45 * CoveRouteClearWidthCm && n.distanceCm < 90.0, "kerb on the path's edge", n.distanceCm);
        // The nearest 1 m station is up to half a metre along the path (1 in 7), or a riser away at a flight.
        Check(std::fabs(k.z - route.stations[n.station].walkZ - 20.0) < 20.0, "kerb 20 cm proud", k.z - route.stations[n.station].walkZ);
    }
    for (const CoveRouteRail& r : route.rails)
    {
        const CoveRoute::Nearest n = route.NearestTo(r.position);
        Check(n.distanceCm > 0.5 * CoveRouteClearWidthCm && n.distanceCm < 110.0, "rail outside the clear width", n.distanceCm);
        Check(r.length > 50.0 && r.length < 320.0, "rail bay length", r.length);
    }

    // Clear of the river, the estate's trees, and anything she'd pick or fell standing on the steps.
    std::vector<Point> riverPts;
    {
        std::vector<Point> shorePts, pathPts;
        auto river = [&](double x, double y) { riverPts.push_back({x, y}); };
        auto lakeShore = [&](double x, double y) { shorePts.push_back({x, y}); };
        auto lakePath = [&](double x, double y) { pathPts.push_back({x, y}); };
#include "Data/HomesteadForageKeepOuts.inc"
    }
    Check(riverPts.size() > 100, "river data", static_cast<double>(riverPts.size()));
    double riverClear = 1e300;
    for (const CoveRouteStation& s : route.stations) riverClear = std::min(riverClear, PolylineDistance(riverPts, s.position));
    Check(riverClear > 600.0, "6 m or more off the river's centreline", riverClear);
    for (const EstatePlacement& p : ProvisionalEstatePlacements().placements)
    {
        const CoveRoute::Nearest n = route.NearestTo(p.position);
        if (p.kind == ResourceKind::ForestTree) Check(n.distanceCm > 200.0, "no tree on the route", p.id);
        if (route.stations[n.station].onSteps) Check(n.distanceCm > 120.0, "nothing growing on the steps", p.id);
        for (const CoveRouteFingerpost& post : route.fingerposts)
            Check(Distance(p.position, post.position) > 150.0, "fingerposts clear of placements", p.id);
    }

    // Fingerposts: outside the front door, and at the head of the cliff steps pointing down them.
    const CoveRouteFingerpost& gate = route.fingerposts[0];
    Check(Distance(gate.position, door) < 2000.0, "a fingerpost outside the front door", Distance(gate.position, door));
    const CoveRoute::Nearest g = route.NearestTo(gate.position);
    Check(g.distanceCm > 90.0 && g.distanceCm < 200.0, "beside the path", g.distanceCm);
    const double pathYaw = std::atan2(route.stations[g.station + 1].position.y - route.stations[g.station].position.y,
                                      route.stations[g.station + 1].position.x - route.stations[g.station].position.x) * 180.0 / Pi;
    Check(YawDifference(gate.yaw, pathYaw) < 20.0, "its arm points down the path", gate.yaw);
    size_t head = 0;
    while (head < route.stations.size() && !route.stations[head].onSteps) ++head;
    const CoveRouteFingerpost& cliff = route.fingerposts[1];
    Check(head < route.stations.size() && Distance(cliff.position, route.stations[head].position) < 400.0,
          "a fingerpost at the head of the cliff steps", cliff.position.x);
    bool pointsDown = false;
    for (const CoveRouteFlight& f : route.flights)
        if (Distance(f.TreadPivot(f.treads), route.stations[head].position) < 150.0) pointsDown = YawDifference(cliff.yaw, f.yaw + 180.0) < 5.0;
    Check(pointsDown, "its arm points down the steps", cliff.yaw);

    // Props' kit on the route (HomesteadCoveRouteKit): one block per tread, the landings covered end to end by
    // whole slabs, every kerb, rail bay and fingerpost, and a pawn blocker along every rail bay.
    {
        const CoveKitLayout& kit = EstateCoveRouteKit();
        const int treads = kit.Count(CoveKitPiece::StepA) + kit.Count(CoveKitPiece::StepB) + kit.Count(CoveKitPiece::StepC);
        Check(treads == route.Steps(), "a block per tread", treads);
        Check(kit.Count(CoveKitPiece::StepA) > 0 && kit.Count(CoveKitPiece::StepB) > 0 && kit.Count(CoveKitPiece::StepC) > 0,
              "all three tread variants used");
        Check(kit.Count(CoveKitPiece::Kerb) == static_cast<int>(route.kerbs.size()), "a piece per kerb");
        const int rails = kit.Count(CoveKitPiece::RailLevel) + kit.Count(CoveKitPiece::Rail26) + kit.Count(CoveKitPiece::Rail28)
            + kit.Count(CoveKitPiece::Rail30);
        Check(rails == static_cast<int>(route.rails.size()), "a piece per rail bay", rails);
        Check(kit.blockers.size() == route.rails.size(), "a blocker per rail bay", static_cast<double>(kit.blockers.size()));
        Check(kit.Count(CoveKitPiece::Fingerpost) == 2, "two fingerposts");
        // An end post closes every rail run, and none stands where a bay continues.
        const int endPosts = kit.Count(CoveKitPiece::RailEndPost);
        Check(endPosts >= 4 && endPosts <= 30, "an end post per free rail end", endPosts);
        std::vector<const CoveKitPlacement*> posts;
        for (const CoveKitPlacement& p : kit.pieces)
            if (p.piece == CoveKitPiece::RailEndPost)
            {
                for (const CoveRouteRail& r : route.rails)
                    Check(Distance(p.position, r.position) >= CoveKitRailJoinCm || std::fabs(p.z - r.z) >= CoveKitRailJoinZCm,
                          "no end post beside a bay's own post", p.position.x);
                for (const CoveKitPlacement* q : posts)
                    Check(Distance(p.position, q->position) >= CoveKitRailJoinCm || std::fabs(p.z - q->z) >= CoveKitRailJoinZCm,
                          "no two end posts together", p.position.x);
                posts.push_back(&p);
            }
        // Every bay's far end has a post: another bay's, or an end post.
        for (const CoveRouteRail& r : route.rails)
        {
            const Point end = Along(r.position, r.yaw, r.length);
            const double endZ = r.z + r.length * std::tan(r.pitch * Pi / 180.0);
            bool posted = false;
            for (const CoveRouteRail& o : route.rails)
                posted = posted || (&o != &r && Distance(o.position, end) < CoveKitRailJoinCm && std::fabs(o.z - endZ) < CoveKitRailJoinZCm);
            for (const CoveKitPlacement* q : posts)
                posted = posted || (Distance(q->position, end) < CoveKitRailJoinCm && std::fabs(q->z - endZ) < CoveKitRailJoinZCm);
            Check(posted, "a post at every bay's far end", end.x);
        }
        double covered = 0.0, total = 0.0, worst = 1.0;
        for (const CoveRouteLanding& l : route.landings) total += l.length;
        for (const CoveKitPlacement& p : kit.pieces)
        {
            if (p.piece == CoveKitPiece::LandingSlab || p.piece == CoveKitPiece::LandingSlab75)
            {
                covered += p.scaleX * (p.piece == CoveKitPiece::LandingSlab75 ? CoveKitLandingSlab75Cm : CoveKitLandingSlabCm);
                worst = std::max(worst, std::max(p.scaleX, 1.0 / p.scaleX));
            }
            const bool rail = p.piece == CoveKitPiece::RailLevel || p.piece == CoveKitPiece::Rail26 || p.piece == CoveKitPiece::Rail28
                || p.piece == CoveKitPiece::Rail30;
            if (rail)
            {
                Check(std::fabs(p.scaleX - p.scaleZ) < 1e-9, "a rail bay scales X and Z together", p.scaleX);
                Check(p.scaleX > 0.3 && p.scaleX < 1.9, "rail bay scale", p.scaleX);
                Check(std::fabs(std::fabs(p.scaleY) - 1.0) < 1e-9, "rail bays mirrored, never stretched across", p.scaleY);
            }
            else if (p.piece != CoveKitPiece::LandingWedge)
                Check(p.scaleY == 1.0 && p.scaleZ == 1.0, "only rails and wedges mirror or scale across", p.scaleY);
        }
        Check(std::fabs(covered - total) < 0.5, "the slabs cover every landing end to end", covered - total);
        Check(worst <= 1.1, "no slab stretched or squeezed more than 10% (Props' limit)", worst);
        // A wedge at each corner landing: at the landing's top, its apex within the landing's end, opening toward
        // the other leg, scaled to the turn.
        Check(route.corners.size() == 2 && kit.Count(CoveKitPiece::LandingWedge) == static_cast<int>(route.corners.size()),
              "a wedge per corner", static_cast<double>(route.corners.size()));
        for (const CoveKitPlacement& p : kit.pieces)
        {
            if (p.piece != CoveKitPiece::LandingWedge) continue;
            const CoveRouteCorner* c = nullptr;
            for (const CoveRouteCorner& k : route.corners)
                if (!c || Distance(k.position, p.position) < Distance(c->position, p.position)) c = &k;
            Check(c && std::fabs(p.z - c->z) < 0.5, "a wedge on its landing's top", p.z);
            Check(c && Distance(p.position, c->position) < 120.0, "a wedge's apex at its corner", c ? Distance(p.position, c->position) : 0.0);
            Check(std::fabs(p.scaleY) > 0.8 && std::fabs(p.scaleY) < 1.05, "a wedge scaled to an 18-21 degree turn", p.scaleY);
            const double yr = p.yaw * Pi / 180.0, a = c ? c->landingYaw * Pi / 180.0 : 0.0;
            // +X along the landing's end edge (across its leg); +Y (after any mirroring) toward its up direction.
            Check(std::fabs(std::cos(yr) * std::cos(a) + std::sin(yr) * std::sin(a)) < 0.02, "a wedge along the landing's end edge", p.yaw);
            const double opens = (p.scaleY < 0.0 ? -1.0 : 1.0) * (-std::sin(yr) * std::cos(a) + std::cos(yr) * std::sin(a));
            Check(opens > 0.99, "a wedge opening toward the other leg", opens);
        }
        int mirrored = 0;
        for (const CoveRouteRail& r : route.rails) mirrored += r.mirrored ? 1 : 0;
        int mirroredPieces = 0;
        for (const CoveKitPlacement& p : kit.pieces) mirroredPieces += p.scaleY < 0.0 ? 1 : 0;
        Check(mirroredPieces == mirrored, "the flagged bays mirrored", mirroredPieces);
        for (size_t i = 0; i < kit.blockers.size() && i < route.rails.size(); ++i)
        {
            const CoveKitBlocker& b = kit.blockers[i];
            const CoveRouteRail& r = route.rails[i];
            const double rise = r.length * std::tan(r.pitch * Pi / 180.0);
            Check(b.z + b.halfHeight >= r.z + rise + 95.0, "the blocker stands above the top rail at its high end", b.z + b.halfHeight);
            Check(b.z - b.halfHeight <= r.z, "the blocker reaches down to the path", b.z - b.halfHeight);
            Check(std::fabs(b.halfLength * 2.0 - r.length) < 0.01, "the blocker runs the bay's length", b.halfLength);
            const CoveRoute::Nearest n = route.NearestTo(b.centre);
            Check(n.distanceCm >= 0.5 * CoveRouteClearWidthCm, "no blocker in the clear width", n.distanceCm);
            // Along its length too, for blockers beside a path (a flight's blockers sit over its own treads' edge).
            if (r.pitch == 0.0)
            {
                double least = 1e300;
                for (int k = 0; k <= 10; ++k)
                    least = std::min(least, PolylineDistance(centreline, Along(b.centre, b.yaw, -b.halfLength + 2.0 * b.halfLength * k / 10.0)));
                Check(least >= 0.5 * CoveRouteClearWidthCm - 2.0, "a path blocker clear of the path along its length", least);
            }
        }
        std::printf("cove kit: %d treads, %d landing slabs (worst stretch %.2f), %d kerbs, %d rail bays (%d mirrored), %d end posts, %zu blockers\n",
                    treads, kit.Count(CoveKitPiece::LandingSlab), worst, kit.Count(CoveKitPiece::Kerb), rails, mirrored, endPosts, kit.blockers.size());
    }

    std::printf("HomesteadCoveRouteTests: %zu stations, %.0f m, %zu flights, %d steps, %zu landings, %zu kerbs, "
                "%zu rail bays; %d failures\n", route.stations.size(), route.Length(), route.flights.size(), route.Steps(),
                route.landings.size(), route.kerbs.size(), route.rails.size(), Failures);
    return Failures == 0 ? 0 : 1;
}
