// Native tests for the cove route (Simulation/HomesteadEstateCoveRoute, generated by
// Scripts/Terrain/cove_route.py): a complete on-foot way from the manor's front door to the cove, within the
// path grade and Props' step kit, protected wherever it's steep, and clear of the river, trees and forage.
#include "../Source/SurvivalGame/Simulation/HomesteadEstate.h"
#include "../Source/SurvivalGame/Simulation/HomesteadEstateCoveRoute.h"
#include "../Source/SurvivalGame/Simulation/HomesteadSimulation.h"

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <vector>

using namespace Homestead;

namespace
{
int Failures = 0;
void Check(bool ok, const char* what, double value = 0.0)
{
    if (!ok)
    {
        std::printf("FAIL: %s (%g)\n", what, value);
        ++Failures;
    }
}
constexpr double Pi = 3.14159265358979323846;
double Distance(Point a, Point b) { return std::hypot(a.x - b.x, a.y - b.y); }
Point Along(Point p, double yaw, double cm) { return {p.x + std::cos(yaw * Pi / 180.0) * cm, p.y + std::sin(yaw * Pi / 180.0) * cm}; }
double YawDifference(double a, double b)
{
    const double d = std::fmod(std::fabs(a - b), 360.0);
    return std::min(d, 360.0 - d);
}
double SegmentDistance(Point a, Point b, Point p)
{
    const double dx = b.x - a.x, dy = b.y - a.y, len2 = dx * dx + dy * dy;
    const double t = len2 > 0.0 ? std::clamp(((p.x - a.x) * dx + (p.y - a.y) * dy) / len2, 0.0, 1.0) : 0.0;
    return Distance(p, {a.x + t * dx, a.y + t * dy});
}
double PolylineDistance(const std::vector<Point>& line, Point p)
{
    double best = 1e300;
    for (size_t i = 0; i + 1 < line.size(); ++i) best = std::min(best, SegmentDistance(line[i], line[i + 1], p));
    return best;
}
const CoveRouteStation* NearestPathStation(const CoveRoute& route, Point p, double& distance)
{
    const CoveRouteStation* best = nullptr;
    distance = 1e300;
    for (const CoveRouteStation& s : route.stations)
    {
        if (s.onSteps) continue;
        const double d = Distance(s.position, p);
        if (d < distance)
        {
            distance = d;
            best = &s;
        }
    }
    return best;
}
}

int main()
{
    const CoveRoute& route = EstateCoveRoute();
    const EstateLayout& layout = ProvisionalEstateLayout();
    Check(route.stations.size() > 400, "centreline stations", static_cast<double>(route.stations.size()));
    Check(route.flights.size() >= 5, "flights", static_cast<double>(route.flights.size()));
    Check(route.fingerposts.size() == 2, "fingerposts", static_cast<double>(route.fingerposts.size()));
    if (route.stations.size() < 2 || route.flights.empty() || route.fingerposts.size() != 2)
    {
        std::printf("HomesteadCoveRouteTests: %d failures\n", Failures);
        return 1;
    }

    // From the manor's front door, outside the ruin, to the sand at the head of the cove.
    const Point door = EstateManorFrontDoor(layout);
    const CoveRouteStation& first = route.stations.front();
    const CoveRouteStation& last = route.stations.back();
    Check(Distance(first.position, door) < 300.0, "starts at the manor's front door", Distance(first.position, door));
    Check(!PointInPolygon(layout.FindPolygon(Anchor::ManorFootprint)->points, first.position), "starts outside the ruin");
    const Point cove = layout.PointOr(Anchor::CoveBeach, {});
    Check(Distance(last.position, cove) < 10000.0, "ends at the cove", Distance(last.position, cove));
    Check(last.walkZ > 100.0 && last.walkZ < 500.0, "ends on the sand, just above the sea", last.walkZ);
    Check(first.walkZ - last.walkZ > 8000.0, "falls the manor's 80-odd metres", first.walkZ - last.walkZ);
    Check(route.Length() > 400.0 && route.Length() < 700.0, "a walk of about half a kilometre", route.Length());

    const std::vector<Point>& boundary = layout.FindPolygon(Anchor::EstateBoundary)->points;
    for (size_t i = 0; i < route.stations.size(); ++i)
    {
        const CoveRouteStation& s = route.stations[i];
        Check(PointInPolygon(boundary, s.position), "on the estate", s.metres);
        if (i == 0) continue;
        const CoveRouteStation& p = route.stations[i - 1];
        const double run = s.metres - p.metres;
        Check(run > 0.0 && run < 1.01, "stations every metre", run);
        // No exposed slope: anything steeper than a path is on steps.
        if (run > 0.5 && std::fabs(s.walkZ - p.walkZ) / (run * 100.0) > CoveRouteMaxPathGrade + 0.01)
            Check(s.onSteps || p.onSteps, "steep only on steps", s.metres);
        // A metre of steps climbs at most 100 / 30 + 1 risers; a metre of path 1 in 7.
        const double most = (s.onSteps || p.onSteps) ? (100.0 / CoveRouteMinGoingCm + 1.0) * CoveRouteMaxRiseCm
                                                     : CoveRouteMaxPathGrade * run * 100.0 + 1.0;
        Check(std::fabs(s.walkZ - p.walkZ) <= most, "no drop between stations", s.metres);
        Check(s.bedZ <= s.walkZ + 0.01, "the ground never above the walk", s.metres);
        if (s.onSteps) Check(s.walkZ - s.bedZ >= 4.9, "the ground cut under the steps", s.metres);
    }
    // Path grades over 2 m or more (chords on its curves).
    for (size_t i = 0; i < route.stations.size(); ++i)
    {
        size_t j = i + 1;
        while (j < route.stations.size() && route.stations[j].metres - route.stations[i].metres < 2.0) ++j;
        if (j >= route.stations.size()) break;
        bool path = true;
        for (size_t k = i; k <= j; ++k) path = path && !route.stations[k].onSteps;
        if (!path) continue;
        const double grade = std::fabs(route.stations[j].walkZ - route.stations[i].walkZ)
            / ((route.stations[j].metres - route.stations[i].metres) * 100.0);
        Check(grade <= CoveRouteMaxPathGrade + 0.005, "path no steeper than 1 in 7", grade);
    }

    // Flights within Props' kit, with landings between, joined to the path or a landing at both ends.
    for (const CoveRouteFlight& f : route.flights)
    {
        Check(f.rise >= CoveRouteMinRiseCm - 0.01 && f.rise <= CoveRouteMaxRiseCm + 0.01, "rise 15-17 cm", f.rise);
        Check(f.going >= CoveRouteMinGoingCm - 0.01 && f.going <= CoveRouteMaxGoingCm + 0.01, "going 30-35 cm", f.going);
        Check(f.treads >= 3 && f.treads <= CoveRouteMaxRisers, "3-12 risers to a flight", f.treads);
        Check(f.railPitch == 26.0 || f.railPitch == 28.0 || f.railPitch == 30.0, "a standard raked rail", f.railPitch);
        Check(std::fabs(f.PitchDegrees() - f.railPitch) <= 1.0, "pitch matches its rail bay", f.PitchDegrees());
        Check(2.0 * f.rise + f.going > 59.0 && 2.0 * f.rise + f.going < 69.0, "2R + G about 64 cm", 2.0 * f.rise + f.going);
        const double footZ = f.z - f.rise;
        const double topZ = f.TreadZ(f.treads - 1);
        const Point topEdge = f.TreadPivot(f.treads);
        bool foot = false, head = false;
        for (const CoveRouteLanding& l : route.landings)
        {
            if (Distance(Along(l.position, l.yaw, l.length), f.start) < 40.0 && std::fabs(l.z - footZ) < 1.0) foot = true;
            if (Distance(l.position, topEdge) < 5.0 && std::fabs(l.z - topZ) < 1.0) head = true;
        }
        double d = 0.0;
        if (const CoveRouteStation* s = NearestPathStation(route, f.start, d); s && d < 110.0 && std::fabs(s->walkZ - footZ) < 20.0)
            foot = true;
        if (const CoveRouteStation* s = NearestPathStation(route, topEdge, d); s && d < 110.0 && std::fabs(s->walkZ - topZ) < 20.0)
            head = true;
        Check(foot, "a flight's foot meets the path or a landing", f.start.x);
        Check(head, "a flight's head meets the path or a landing", f.start.x);
        // A rail down its drop side, the flight's whole length.
        double railed = 0.0;
        const Point end = f.TreadPivot(f.treads);
        for (const CoveRouteRail& r : route.rails)
            if (r.pitch == f.railPitch && YawDifference(r.yaw, f.yaw) < 0.5 && SegmentDistance(f.start, end, r.position) < 100.0)
                railed += r.length;
        Check(railed >= 0.95 * f.treads * f.going, "every flight railed", railed);
    }
    for (const CoveRouteLanding& l : route.landings) Check(l.length >= CoveRouteMinLandingCm, "landings at least 1.2 m", l.length);
    Check(route.Steps() >= 100, "steps down the valley side", route.Steps());

    // Kerbs and rails stand outside the 1.4 m clear width, on the path.
    for (const CoveRouteKerb& k : route.kerbs)
    {
        const CoveRoute::Nearest n = route.NearestTo(k.position);
        Check(n.distanceCm > 0.45 * CoveRouteClearWidthCm && n.distanceCm < 90.0, "kerb on the path's edge", n.distanceCm);
        // The nearest 1 m station is up to half a metre along the path (1 in 7), or a riser away at a flight.
        Check(std::fabs(k.z - route.stations[n.station].walkZ - 20.0) < 20.0, "kerb 20 cm proud", k.z - route.stations[n.station].walkZ);
    }
    for (const CoveRouteRail& r : route.rails)
    {
        const CoveRoute::Nearest n = route.NearestTo(r.position);
        Check(n.distanceCm > 0.5 * CoveRouteClearWidthCm && n.distanceCm < 110.0, "rail outside the clear width", n.distanceCm);
        Check(r.length > 50.0 && r.length < 320.0, "rail bay length", r.length);
    }

    // Clear of the river, the estate's trees, and anything she'd pick or fell standing on the steps.
    std::vector<Point> riverPts;
    {
        std::vector<Point> shorePts, pathPts;
        auto river = [&](double x, double y) { riverPts.push_back({x, y}); };
        auto lakeShore = [&](double x, double y) { shorePts.push_back({x, y}); };
        auto lakePath = [&](double x, double y) { pathPts.push_back({x, y}); };
#include "Data/HomesteadForageKeepOuts.inc"
    }
    Check(riverPts.size() > 100, "river data", static_cast<double>(riverPts.size()));
    double riverClear = 1e300;
    for (const CoveRouteStation& s : route.stations) riverClear = std::min(riverClear, PolylineDistance(riverPts, s.position));
    Check(riverClear > 600.0, "6 m or more off the river's centreline", riverClear);
    for (const EstatePlacement& p : ProvisionalEstatePlacements().placements)
    {
        const CoveRoute::Nearest n = route.NearestTo(p.position);
        if (p.kind == ResourceKind::ForestTree) Check(n.distanceCm > 200.0, "no tree on the route", p.id);
        if (route.stations[n.station].onSteps) Check(n.distanceCm > 120.0, "nothing growing on the steps", p.id);
        for (const CoveRouteFingerpost& post : route.fingerposts)
            Check(Distance(p.position, post.position) > 150.0, "fingerposts clear of placements", p.id);
    }

    // Fingerposts: outside the front door, and at the head of the cliff steps pointing down them.
    const CoveRouteFingerpost& gate = route.fingerposts[0];
    Check(Distance(gate.position, door) < 2000.0, "a fingerpost outside the front door", Distance(gate.position, door));
    const CoveRoute::Nearest g = route.NearestTo(gate.position);
    Check(g.distanceCm > 90.0 && g.distanceCm < 200.0, "beside the path", g.distanceCm);
    const double pathYaw = std::atan2(route.stations[g.station + 1].position.y - route.stations[g.station].position.y,
                                      route.stations[g.station + 1].position.x - route.stations[g.station].position.x) * 180.0 / Pi;
    Check(YawDifference(gate.yaw, pathYaw) < 20.0, "its arm points down the path", gate.yaw);
    size_t head = 0;
    while (head < route.stations.size() && !route.stations[head].onSteps) ++head;
    const CoveRouteFingerpost& cliff = route.fingerposts[1];
    Check(head < route.stations.size() && Distance(cliff.position, route.stations[head].position) < 400.0,
          "a fingerpost at the head of the cliff steps", cliff.position.x);
    bool pointsDown = false;
    for (const CoveRouteFlight& f : route.flights)
        if (Distance(f.TreadPivot(f.treads), route.stations[head].position) < 150.0) pointsDown = YawDifference(cliff.yaw, f.yaw + 180.0) < 5.0;
    Check(pointsDown, "its arm points down the steps", cliff.yaw);

    std::printf("HomesteadCoveRouteTests: %zu stations, %.0f m, %zu flights, %d steps, %zu landings, %zu kerbs, "
                "%zu rail bays; %d failures\n", route.stations.size(), route.Length(), route.flights.size(), route.Steps(),
                route.landings.size(), route.kerbs.size(), route.rails.size(), Failures);
    return Failures == 0 ? 0 : 1;
}
