#pragma once

// Generated by Scripts/Audio/Measure-Loudness.py from the source files; do not edit by hand.
// LUFS at unity gain, EBU R128 K-weighted: integrated (-70 when too short to gate), momentary max
// (400 ms) and short-term max (3 s). Read by Tests/HomesteadAudioLevelTests.cpp.
namespace Homestead
{
namespace AudioLevels
{
struct Measurement
{
    const char* source;
    double integratedLufs;
    double momentaryMaxLufs;
    double shortTermMaxLufs;
};
inline constexpr Measurement Measurements[] = {
    {"Audio/Ambience/CreekLoop.wav", -27.5, -24.4, -26.2},
    {"Audio/Ambience/HearthCrackle.wav", -29.4, -25.6, -27.9},
    {"Audio/Ambience/RainLoop.wav", -19.1, -17.2, -18.3},
    {"Audio/Effects/CaneCutA.wav", -26.0, -22.6, -31.4},
    {"Audio/Effects/CaneCutB.wav", -26.6, -23.1, -31.8},
    {"Audio/Effects/CaneCutC.wav", -25.4, -22.3, -31.0},
    {"Audio/Effects/ChopA.wav", -70.0, -25.3, -34.0},
    {"Audio/Effects/ChopB.wav", -70.0, -25.5, -34.3},
    {"Audio/Effects/ChopC.wav", -70.0, -23.0, -31.8},
    {"Audio/Effects/ScytheSwish.wav", -19.9, -17.4, -26.1},
    {"Audio/Effects/TreeFall.wav", -24.2, -20.1, -28.8},
    {"Audio/Footsteps/BareStepRun_00.wav", -70.0, -24.8, -33.5},
    {"Audio/Footsteps/BareStepRun_01.wav", -70.0, -22.3, -31.0},
    {"Audio/Footsteps/BareStepRun_02.wav", -70.0, -24.0, -32.7},
    {"Audio/Footsteps/BareStepRun_03.wav", -70.0, -23.3, -32.1},
    {"Audio/Footsteps/BareStepWalk_00.wav", -70.0, -23.4, -32.1},
    {"Audio/Footsteps/BareStepWalk_01.wav", -70.0, -23.3, -32.1},
    {"Audio/Footsteps/BareStepWalk_02.wav", -70.0, -22.6, -31.4},
    {"Audio/Footsteps/BareStepWalk_03.wav", -70.0, -22.9, -31.6},
    {"Audio/Footsteps/BareStepWalk_04.wav", -70.0, -24.2, -33.0},
    {"Audio/Footsteps/BareStepWalk_05.wav", -70.0, -23.6, -32.3},
    {"Source/a-new-town/ANewTown.mp3", -15.7, -9.5, -12.8},
    {"Source/evening-harp/EveningHarp.mp3", -19.4, -11.6, -13.8},
    {"Source/forest-ambience/ForestAmbience.mp3", -46.3, -38.3, -43.0},
    {"Source/kenney-impact/CraftStrikeA.ogg", -70.0, -15.9, -24.7},
    {"Source/kenney-impact/CraftStrikeB.ogg", -70.0, -16.7, -25.5},
    {"Source/kenney-impact/CraftStrikeC.ogg", -70.0, -17.4, -26.2},
    {"Source/kenney-impact/GrassStepA.ogg", -25.7, -25.7, -34.5},
    {"Source/kenney-impact/GrassStepB.ogg", -24.9, -24.9, -33.7},
    {"Source/kenney-impact/WoodTapA.ogg", -70.0, -22.0, -30.8},
    {"Source/kenney-impact/WoodTapB.ogg", -70.0, -24.2, -32.9},
    {"Source/kenney-interface/UIClick.ogg", -70.0, -29.5, -38.2},
    {"Source/medieval-theme/MedievalTheme.mp3", -15.7, -10.1, -13.0},
    {"Source/whispers-of-the-glen/WhispersOfTheGlen.mp3", -14.7, -9.1, -11.2},
};
}
}
