"""Homestead: the heroine's homespun wardrobe, a second batch of skinned garments on her MetaHuman body.

    SKM_LinenTee        plain linen T-tunic shirt (woad blue-grey), crew neck, mid-upper-arm sleeves
    SKM_LinenLongShirt  fitted unbleached linen shirt, laced slit neck, gathered cuffs
    SKM_WoolTrousers    walnut-brown homespun wool twill, drawstring waist, boot-close below the knee
    SKM_FurCoat         sheepskin coat, hair side in, suede outside, fur collar/cuffs/front edges,
                        horn toggles on leather loops, ~2 cm of loft

Reproducible, seeded Blender 5.2 build (headless), from the repo root:

    & "C:\\Program Files\\Blender Foundation\\Blender 5.2\\blender.exe" --background --factory-startup `
        --python Scripts\\Blender\\Recipes\\clothing_wardrobe.py -- --stage all

Stages: ``fit`` (fitted meshes + Workbench previews only), ``build`` (fit, wrinkles, UVs, textures,
weights, thickness, accessories, test poses, FBX, coverage masks, report, .blend), ``render``
(4K Cycles review renders from the saved .blend), ``all``.

Inputs: the coordinator's Unreal exports of the heroine's un-culled MetaHuman body and face
(``E:\\Repos\\HomesteadShared\\MetaHumanBody``, cm, Z up, -Y forward, ``metahuman_base_skel``), the
base-layer shorts ``Assets/Characters/PrimitiveOutfit/SKM_PrimitiveShorts.fbx`` (the shirts'
hems must clear its waistband) and the cord belt's contour
``Assets/Props/CordBelt/cord_belt_contour.json`` (hems end just above the belt).
Outputs: ``Assets/Characters/Clothing/<Garment>/`` plus shared renders, report and .blend.

Setting and research notes. Pre-industrial countryside: every fabric is hand-spun and
hand-woven. Linen shirts are cut from rectangles (T-tunic: body, sleeves, gussets), plain
(tabby) weave of 12-16 threads/cm for fine shirting, 9-11 for everyday; closures are cords and
ties, necks are bound or faced and a slit is laced through worked eyelets. Wool for trousers is
a 2/2 twill, fulled (felted in finishing) so the weave softens under a light nap, dyed with
walnut hulls (warm browns). Sheepskin coats are worn hair side in: the flesh side is buffed
to suede, seams are butted or felled with sinew/linen thread, and the fleece is turned out at
collar, cuffs and front edges; closures are horn or wooden toggles through leather loops.

PROVENANCE: all garment geometry and textures are original and generated by this script
(numpy procedural maps). Review renders use the CC0 Poly Haven HDRI "Kloofendal 48d Partly
Cloudy (Pure Sky)" for lighting only.
"""
import argparse
import json
import math
import sys
import time
from pathlib import Path

import bpy
import numpy as np

HERE = Path(__file__).resolve()
sys.path.insert(0, str(HERE.parent))

from outfit import body as B  # noqa: E402
from outfit import layers as Ly  # noqa: E402
from outfit import tops as Tp  # noqa: E402
from outfit import trousers as Tr  # noqa: E402
from outfit.garments import boundary_loops, edges_of  # noqa: E402

ROOT = HERE.parents[3]
INPUT_DIR = Path(r"E:\Repos\HomesteadShared\MetaHumanBody")
BODY_FBX = INPUT_DIR / "SKM_MHC_Heroine_BodyMesh_Full.fbx"
FACE_FBX = INPUT_DIR / "SKM_MHC_Heroine_FaceMesh.fbx"
SHORTS_FBX = ROOT / "Assets" / "Characters" / "PrimitiveOutfit" / "SKM_PrimitiveShorts.fbx"
TANK_FBX = ROOT / "Assets" / "Characters" / "PrimitiveOutfit" / "SKM_PrimitiveTankTop.fbx"
BELT_JSON = ROOT / "Assets" / "Props" / "CordBelt" / "cord_belt_contour.json"
POUCH_FBX = ROOT / "Assets" / "Props" / "ForagePouch" / "SM_ForagePouch.fbx"
POUCH_FIT = ROOT / "Assets" / "Props" / "ForagePouch" / "forage_pouch_fit.json"
BELT_FBX = ROOT / "Assets" / "Props" / "CordBelt" / "SM_CordBelt.fbx"
OUT = ROOT / "Assets" / "Characters" / "Clothing"
RENDERS = OUT / "Renders"
WORK = OUT / "_work"
BLEND = OUT / "Clothing.blend"
HDRI = ROOT / "Assets" / "Source" / "Blender" / "polyhaven" / "kloofendal_48d_partly_cloudy_puresky_2k.exr"
SEED = 20260927
ORDER = ("SKM_WoolTrousers", "SKM_LinenTee", "SKM_LinenLongShirt", "SKM_FurCoat")
THICKNESS = {  # cloth (m): base, at hems/edges
    "SKM_WoolTrousers": (0.0019, 0.0034),
    "SKM_LinenTee": (0.0011, 0.0026),
    "SKM_LinenLongShirt": (0.0009, 0.0024),
    "SKM_FurCoat": (0.020, 0.026),
}
T0 = time.time()
# Jenny (2026-10-04): every garment fits her frame as closely as the starter tank top and shorts
# (3.2 mm off the skin), tight and fitted rather than falling straight from the bust. These override
# the shared outfit defaults (which the clerk's looser shirt and trousers keep).
FITTED = {
    "tee": dict(base=0.0030, hang=0.06, sleeve_ease=0.0030, fold_amp=0.0009, sleeve_fold=0.0008),
    "longshirt": dict(base=0.0032, hang=0.10, sleeve_ease=0.0045, cuff_ease=0.0025, fold_amp=0.0014,
                      sleeve_fold=0.0016),
    "coat": dict(base=0.008, hang=0.22, sleeve_ease=0.009, cuff_ease=0.010, fold_amp=0.0016, sleeve_fold=0.0016),
    "trousers": dict(offset=0.0030, crotch_ease=0.0040, thigh_ease=0.0003),
}
LEG_DRAPE_K = 0.08  # the thigh hugs the leg instead of falling from the hip's widest girth


def log(msg):
    print(f"[wardrobe {time.time() - T0:7.1f}s] {msg}", flush=True)


def link(obj, coll=None):
    (coll or bpy.context.scene.collection).objects.link(obj)
    return obj


# ------------------------------------------------------------------ geometry

def vertex_normals(V, F):
    N = np.zeros_like(V)
    for k in range(4):
        a, b, c = F[:, k], F[:, (k + 1) % 4], F[:, (k + 3) % 4]
        N_ = np.cross(V[b] - V[a], V[c] - V[a])
        np.add.at(N, a, N_)
    return N / np.maximum(np.linalg.norm(N, axis=1, keepdims=True), 1e-12)


def orient_out(V, F, body_surf):
    """Make the quad winding consistent across the whole garment (topologically, so faces on the
    inside of a sleeve next to the torso can't be misjudged), then flip everything if most faces
    point into the body."""
    import bmesh
    bm = bmesh.new()
    vs = [bm.verts.new(v) for v in V]
    for f in F:
        bm.faces.new([vs[i] for i in f])
    bm.faces.ensure_lookup_table()
    bmesh.ops.recalc_face_normals(bm, faces=bm.faces)
    F2 = np.array([[v.index for v in f.verts] for f in bm.faces], np.int64)
    bm.free()
    cent = V[F2].mean(1)
    fn = np.cross(V[F2[:, 1]] - V[F2[:, 0]], V[F2[:, 3]] - V[F2[:, 0]])
    _, _, bn = body_surf.signed(cent)
    if ((fn * bn).sum(1) > 0).mean() < 0.5:
        F2 = F2[:, ::-1].copy()
    return F2


def shell_layer(V, F, thick, name):
    """Approximate outer shell (fitted surface pushed out by the cloth thickness) as a layer."""
    N = vertex_normals(V, F)
    Vo = V + N * np.broadcast_to(thick, (len(V),))[:, None]
    T = np.concatenate([F[:, [0, 1, 2]], F[:, [0, 2, 3]]])
    return Ly.LayerSurface(Vo, N, T, name)


def mesh_layer(obj, body_surf):
    return Ly.outer_shell(obj, body_surf)


class Wrapped:
    """MultiSurface -> the 4-tuple constraint interface."""

    def __init__(self, ms):
        self.ms = ms

    def signed(self, pts):
        s, loc, nrm = self.ms.signed(pts)
        return s, loc, nrm, np.ones(len(pts), bool)


class MultiSurface:
    def __init__(self, surfs, labels):
        self.surfs, self.labels = surfs, labels

    def signed(self, pts, idx=None):
        lab = self.labels if idx is None else self.labels[idx]
        s = np.empty(len(pts)); loc = np.empty_like(pts); nrm = np.empty_like(pts)
        for i, surf in enumerate(self.surfs):
            m = lab == i
            if m.any():
                s[m], loc[m], nrm[m] = surf.signed(pts[m])
        return s, loc, nrm


class Labelled:
    """Per-vertex surface choice for the relax (which passes all vertices in order)."""

    def __init__(self, surfs, labels):
        self.ms = MultiSurface(surfs, labels)

    def signed(self, pts):
        s, loc, nrm = self.ms.signed(pts)
        return s, loc, nrm, np.ones(len(pts), bool)


# ------------------------------------------------------------------- fitting

def smooth_edges(V, F, loops, fixed, cons, hem_axis=None, iters=8):
    """Iron the open edges: smooth each boundary polyline, put it back outside the body and the
    layers below, then let the panel settle round the pinned edge."""
    V = V.copy()
    for lp in loops:
        P = V[lp]
        for _ in range(iters):
            P = P + 0.5 * (0.5 * (np.roll(P, 1, 0) + np.roll(P, -1, 0)) - P)
        V[lp] = P
    V = Ly.collide_layers(V, cons, rounds=2)
    V, _ = Ly.relax_layers(V, F, fixed, cons, hem_axis=hem_axis, iters=25, pinned=fixed)
    return V


def fit_trousers(body, layers):
    p = Tr.trousers_params(body)
    p.update(FITTED["trousers"])
    g = Tr.build_trousers(body, p)
    V, F = g.arrays()
    F = orient_out(V, F, body.all)
    loops = boundary_loops(F, len(V))
    fixed = np.zeros(len(V), bool)
    for lp in loops:
        fixed[lp] = True
    lab = Tr.trouser_labels(g, V)
    off = Tr.trouser_offsets(g, V, body)
    cons = [(Labelled([body.torso, body.leg_l, body.leg_r], lab), off, None),
            (Tr.LegDrape(body, p, "l", k=LEG_DRAPE_K), np.zeros(len(V)), lab == 1),
            (Tr.LegDrape(body, p, "r", k=LEG_DRAPE_K), np.zeros(len(V)), lab == 2),
            (Tr.Plane(1.0, 0.0022), np.zeros(len(V)), lab == 1),
            (Tr.Plane(-1.0, 0.0022), np.zeros(len(V)), lab == 2)]
    V, gaps = Ly.relax_layers(V, F, fixed, cons, iters=170, log=log)
    V = smooth_edges(V, F, loops, fixed, cons)
    gaps = [cons[0][0].signed(V)[0]]
    g.extra.update(labels=lab, loops=loops, gap=gaps[0], offsets=off, constraints=cons)
    log(f"{g.name}: {len(V)} verts, {len(F)} quads, loops {[len(l) for l in loops]}, "
        f"gap mm min {1000 * gaps[0].min():.2f} median {1000 * np.median(gaps[0]):.2f}")
    return g, V, F


def top_offsets(g, V, body, prof):
    p = g.extra["params"]
    reg = g.extra["region"]
    off = np.full(len(V), p["base"])
    sl = (reg == 1) | (reg == 2)
    off[sl] = p["sleeve_ease"]
    if p.get("cuff"):
        s = g.extra["axial"]
        for side in ("l", "r"):
            m = reg == (1 if side == "l" else 2)
            s_end = g.extra["sleeves"][side]["s_end"]
            u = np.clip((s_end - p["cuff"] - s[m]) / 0.05, 0, 1)
            off[m] = p["cuff_ease"] + (p["sleeve_ease"] - p["cuff_ease"]) * u
    if (reg == 3).any():
        off[reg == 3] = p["collar"]["off"]
    return off


def fit_top(body, kind, belt, layers, prof):
    p = Tp.top_params(body, kind, belt)
    p.update(FITTED[kind])
    g = Tp.build_top(body, p)
    V, F = g.arrays()
    F = orient_out(V, F, body.all)
    loops = boundary_loops(F, len(V))
    fixed = np.zeros(len(V), bool)
    for lp in loops:
        fixed[lp] = True
    off = top_offsets(g, V, body, prof)
    cons = [(Ly.ClosedSurface(body.all), off, None),
            (Ly.Drape(prof, p["hang"], p["ua_z"] + 0.03, p["base"]), np.zeros(len(V)), g.extra["region"] == 0)]
    low = V[:, 2] < 1.16
    for lay, loff in layers:
        cons.append((lay, np.full(len(V), loff), low if kind != "coat" else None))
    V, gaps = Ly.relax_layers(V, F, fixed, cons, hem_axis=g.extra["hem_axis"],
                              iters=200 if kind == "coat" else 170, log=log)
    V = smooth_edges(V, F, loops, fixed, cons, hem_axis=g.extra["hem_axis"])
    gaps = [body.all.signed(V)[0]]
    g.extra.update(loops=loops, gap=gaps[0], offsets=off, constraints=cons)
    log(f"{g.name}: {len(V)} verts, {len(F)} quads, loops {[len(l) for l in loops]}, "
        f"body gap mm min {1000 * gaps[0].min():.2f} median {1000 * np.median(gaps[0]):.2f}")
    # openings
    for key in ("slit", "opening"):
        if not p.get(key):
            continue
        n0 = len(V)
        if key == "slit":
            top = V[Tp.front_column(g)[-1], 2]
            z0 = top - p["slit"]
            V, F, le, ri = Tp.split_front(g, V, F, z0)
            V = Tp.spread_opening(V, le, ri, lambda v: 0.5 * p["slit_open"] * np.clip((v[2] - z0) / p["slit"], 0, 1) ** 1.3)
        else:
            V, F, le, ri = Tp.split_front(g, V, F, -1.0)
            V = Tp.spread_opening(V, le, ri, lambda v: p["open_gap"])
        g.extra[key] = (le, ri)
        src = np.concatenate([np.arange(n0), np.array(le, np.int64)])
        for k in ("region", "axial", "hem_axis", "gap", "offsets"):
            g.extra[k] = g.extra[k][src]
        g.extra["constraints"] = [(s, np.asarray(o)[src], None if m is None else m[src]) for s, o, m in cons]
        g.extra["src_map"] = src
    g.extra["loops"] = boundary_loops(F, len(V))
    return g, V, F


def garment_object(g, V, F, body):
    F = orient_out(V, F, body.all)
    me = bpy.data.meshes.new(g.name)
    me.from_pydata(V.tolist(), [], F.tolist())
    me.update()
    me.shade_smooth()
    panel = me.attributes.new("panel", "INT", "FACE")
    panel.data.foreach_set("value", np.array(g.face_panel, np.int32))
    for e in me.edges:
        a, b = sorted(e.vertices)
        e.use_seam = (a, b) in g.uv_seams
    return link(bpy.data.objects.new(g.name, me)), F


def fit_all(body, belt, shorts_obj, want=None):
    prof = Ly.RadialProfile(body, 0.98, 1.36)
    shorts_layer = mesh_layer(shorts_obj, body.all)
    out = {}
    g, V, F = fit_trousers(body, [])
    out[g.name] = (g, V, F)
    tr_layer = shell_layer(V, F, THICKNESS[g.name][0], g.name)
    shirt_layers = [(shorts_layer, 0.0030), (tr_layer, 0.0030)]
    for kind in ("tee", "longshirt"):
        if want and kind not in want and "coat" not in want:
            continue
        g, V, F = fit_top(body, kind, belt, shirt_layers, prof)
        out[g.name] = (g, V, F)
    if want and "coat" not in want:
        return out
    coat_layers = [(shorts_layer, 0.0035), (tr_layer, 0.0035)]
    for name in ("SKM_LinenTee", "SKM_LinenLongShirt"):
        gg, VV, FF = out[name]
        coat_layers.append((shell_layer(VV, FF, THICKNESS[name][0], name), 0.0040))
    g, V, F = fit_top(body, "coat", belt, coat_layers, prof)
    out[g.name] = (g, V, F)
    return out


# ------------------------------------------------------------------- preview

COLORS = {"SKM_WoolTrousers": (0.35, 0.24, 0.16, 1), "SKM_LinenTee": (0.45, 0.52, 0.58, 1),
          "SKM_LinenLongShirt": (0.85, 0.82, 0.72, 1), "SKM_FurCoat": (0.62, 0.45, 0.30, 1)}


def preview(show, path, views=(("front", (0, -4, 1.0), (90, 0, 0)), ("side", (4, 0, 1.0), (90, 0, 90)),
                               ("back", (0, 4, 1.0), (90, 0, 180))), scale=1.55):
    sc = bpy.context.scene
    sc.render.engine = "BLENDER_WORKBENCH"
    sc.display.shading.light = "STUDIO"
    sc.display.shading.color_type = "OBJECT"
    sc.render.resolution_x, sc.render.resolution_y = 900, 1300
    for o in sc.objects:
        if o.type == "MESH":
            o.hide_render = o.name not in show and not o.name.startswith("SKM_MHC")
            o.color = COLORS.get(o.name, (0.75, 0.58, 0.48, 1))
    cam = bpy.data.objects.get("PreviewCam") or link(bpy.data.objects.new("PreviewCam", bpy.data.cameras.new("PreviewCam")))
    cam.data.type = "ORTHO"
    cam.data.ortho_scale = scale
    sc.camera = cam
    for name, loc, rot in views:
        cam.location = loc
        cam.rotation_euler = [math.radians(a) for a in rot]
        sc.render.filepath = str(path).replace(".png", f"_{name}.png")
        bpy.ops.render.render(write_still=True)


# ---------------------------------------------------------------------- main

def load_inputs():
    bpy.ops.wm.read_factory_settings(use_empty=True)
    arm, meshes = B.import_skeletal(BODY_FBX)
    arm.name = "root"
    body_obj = meshes[0]
    body_obj.name = "SKM_MHC_Heroine_BodyMesh"
    face_arm, face_meshes = B.import_skeletal(FACE_FBX)
    face_arm.name = "FaceRig"
    face_obj = face_meshes[0]
    face_obj.name = "SKM_MHC_Heroine_FaceMesh"
    body = B.Body(arm, body_obj, extra=[face_obj])
    base = {}
    for path, name in ((SHORTS_FBX, "SKM_PrimitiveShorts"), (TANK_FBX, "SKM_PrimitiveTankTop")):
        a2, ms = B.import_skeletal(path)
        obj = ms[0]
        obj.name = name
        mw = obj.matrix_world.copy()
        obj.parent = arm
        obj.matrix_world = mw
        for mod in obj.modifiers:
            if mod.type == "ARMATURE":
                mod.object = arm
        ad = a2.data
        bpy.data.objects.remove(a2)
        bpy.data.armatures.remove(ad)
        base[name] = obj
    belt = Tp.Belt(json.loads(BELT_JSON.read_text()))
    return arm, body_obj, face_obj, body, base, belt


def main():
    argv = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
    ap = argparse.ArgumentParser()
    ap.add_argument("--stage", default="all", choices=["fit", "build", "render", "all"])
    ap.add_argument("--samples", type=int, default=192)
    ap.add_argument("--reuse-textures", action="store_true")
    ap.add_argument("--only", nargs="*")
    ap.add_argument("--garments", nargs="*", help="fit stage: tee longshirt coat (trousers always)")
    args = ap.parse_args(argv)
    if args.stage == "render":
        render_stage(args)
        return
    np.random.seed(SEED)
    WORK.mkdir(parents=True, exist_ok=True)
    arm, body_obj, face_obj, body, base, belt = load_inputs()
    log("landmarks " + json.dumps({k: (np.round(v, 4).tolist() if isinstance(v, list) else round(v, 4))
                                  for k, v in body.lm.items()}))
    fitted = fit_all(body, belt, base["SKM_PrimitiveShorts"], args.garments)
    objs = {}
    for name, (g, V, F) in fitted.items():
        obj, F2 = garment_object(g, V, F, body)
        fitted[name] = (g, V, F2)
        objs[name] = obj
    if args.stage == "fit":
        for name in objs:
            if name == "SKM_WoolTrousers":
                preview({name}, WORK / f"fit_{name}.png",
                        views=(("front", (0, -4, 0.6), (90, 0, 0)), ("side", (4, 0, 0.6), (90, 0, 90)),
                               ("back", (0, 4, 0.6), (90, 0, 180))), scale=1.25)
            else:
                preview({name}, WORK / f"fit_{name}.png")
        if "SKM_FurCoat" in objs:
            preview({"SKM_WoolTrousers", "SKM_LinenLongShirt", "SKM_FurCoat"}, WORK / "fit_layered.png")
        if "SKM_LinenLongShirt" in objs:
            preview({"SKM_LinenLongShirt"}, WORK / "zoom_ls.png",
                    views=(("waist", (4, 0, 1.15), (90, 0, 90)), ("arm", (0.22, -4, 1.25), (90, 0, 0)),
                           ("neck", (0.0, -4, 1.42), (90, 0, 0))), scale=0.45)
        bpy.ops.wm.save_as_mainfile(filepath=str(WORK / "fit.blend"))
        return
    build(args, arm, body_obj, face_obj, body, base, fitted, objs)
    if args.stage == "all":
        render_stage(args)


# ======================================================================= build

from outfit import coat_tex as CT  # noqa: E402
from outfit import detail as D  # noqa: E402
from outfit import render as Rn  # noqa: E402
from outfit import rig as R  # noqa: E402
from outfit import wardrobe_detail as WD  # noqa: E402
from outfit import wardrobe_rig as WR  # noqa: E402
from outfit import wardrobe_tex as WT  # noqa: E402

EDGE_NAMES = {"trousers": ("waist", "leghem"), "tee": ("hem", "cuff", "neck"), "longshirt": ("hem", "cuff", "neck"),
              "tank": ("hem", "neck"),
              "coat": ("hem", "cuff", "collartop", "opening")}
BASE_TEX = ROOT / "Assets" / "Characters" / "PrimitiveOutfit" / "Textures"


def gdir(name):
    return OUT / name.replace("SKM_", "")


def make_material(name, paths):
    import primitive_outfit as PO
    return PO.make_material(name, paths)


def set_verts(obj, V):
    obj.data.vertices.foreach_set("co", np.asarray(V, np.float32).ravel())
    obj.data.update()


def collide_constraints(g, V, body, layers):
    kind = g.extra["params"]["kind"]
    if kind == "trousers":
        lab = g.extra["labels"]
        off = np.maximum(0.0030, 0.85 * g.extra["offsets"])
        return [(Labelled([body.torso, body.leg_l, body.leg_r], lab), off, None),
                (Tr.Plane(1.0, 0.0018), np.zeros(len(V)), lab == 1),
                (Tr.Plane(-1.0, 0.0018), np.zeros(len(V)), lab == 2)]
    off = np.maximum(0.0028 if kind != "coat" else 0.009, 0.6 * g.extra["offsets"])
    cons = [(Ly.ClosedSurface(body.all), off, None)]
    low = V[:, 2] < 1.16
    for lay, loff in layers:
        cons.append((lay, np.full(len(V), loff), low if kind != "coat" else None))
    return cons


def detail(g, V, F, obj, body, layers):
    polys, _ = WD.edge_polylines(g, V, F)
    for k, lst in g.features.items():
        polys.setdefault(k, []).extend(lst)
    fields = WD.fields_for(V, polys)
    h = WD.wrinkles(g, V, fields, body, SEED)
    _, _, n = body.all.signed(V)
    V2 = Ly.collide_layers(V + n * h[:, None], collide_constraints(g, V, body, layers), rounds=2)
    set_verts(obj, V2)
    fields = WD.fields_for(V2, polys)
    gap = body.all.signed(V2)[0]
    log(f"{g.name}: wrinkles {1000 * np.abs(h).max():.1f} mm max, skin gap mm min {1000 * gap.min():.2f} "
        f"median {1000 * np.median(gap):.2f}")
    return V2, fields, gap


def limb_blend(g, V):
    kind = g.extra["params"]["kind"]
    if kind == "trousers":
        lab = g.extra["labels"]
        w = D._smooth(g.extra["params"]["junction_z"] - V[:, 2], 0.02, 0.08)
        return {("leg", "l"): w * (lab == 1), ("leg", "r"): w * (lab == 2)}
    reg, ax = g.extra["region"], g.extra["axial"]
    w = D._smooth(ax, 0.03, 0.10)
    return {("arm", "l"): w * (reg == 1), ("arm", "r"): w * (reg == 2)}


def edge_group(obj, edge, name="_edge"):
    vg = obj.vertex_groups.new(name=name)
    for i, d in enumerate(edge):
        vg.add([i], float(np.clip(d / 0.05, 0, 1)), "REPLACE")


def read_group(obj, name, scale=1.0):
    eg = obj.vertex_groups[name]
    e = np.zeros(len(obj.data.vertices))
    for v in obj.data.vertices:
        for gg in v.groups:
            if gg.group == eg.index:
                e[v.index] = gg.weight * scale
    obj.vertex_groups.remove(eg)
    return e


def join_parts(obj, parts, src):
    for p in parts:
        R.transfer_weights(p, src)
        pn, pw = R.read_weights(p)
        R.write_weights(p, pn, R.clean_weights(pw))
        p.data.materials.append(obj.data.materials[0])
    bpy.ops.object.select_all(action="DESELECT")
    for p in parts:
        p.select_set(True)
    obj.select_set(True)
    bpy.context.view_layer.objects.active = obj
    if parts:
        bpy.ops.object.join()


def attach(obj, arm):
    mod = obj.modifiers.new("Armature", "ARMATURE")
    mod.object = arm
    obj.parent = arm


def build_cloth(name, g, V, F, obj, body, layers, src, limb, arm, rng):
    kind = g.extra["params"]["kind"]
    short = name.replace("SKM_", "")
    V, fields, gap = detail(g, V, F, obj, body, layers)
    uvpm = D.unwrap(obj)
    tdir = gdir(name) / "Textures"
    tdir.mkdir(parents=True, exist_ok=True)
    extra, eye = {}, None
    if kind == "longshirt":
        sV, sN, sT = B.mesh_arrays(obj, evaluated=False)
        eye = WR.eyelets(g, V, B.Surface(sV, sN, sT))
        extra["eyelets"] = np.array(eye["l"] + eye["r"])
    if kind == "trousers" and g.extra["params"].get("knee_patch", True):
        kn = body.bones["calf_l"][0]
        target = np.array([kn[0], kn[1] - 0.07, kn[2] + 0.02])
        c = V[np.argmin(np.linalg.norm(V - target, axis=1))]
        extra["patch"] = (c, (0.046, 0.037), 0.0)
    cached = WORK / f"tex_{short}.json"
    if REUSE["tex"] and cached.exists():
        prev = json.loads(cached.read_text())
        paths = {k: Path(v) for k, v in prev["paths"].items()}
        stats = prev["stats"]
        log(f"{name}: reusing textures")
    else:
        paths, stats = WT.compose_cloth(obj, fields, uvpm, tdir, short, R_out=2048, supersample=2, seed=SEED,
                                        log=log, **extra)
        cached.write_text(json.dumps(dict(paths={k: str(v) for k, v in paths.items()}, stats=stats)))
    mat = make_material("M_" + short, paths)
    obj.data.materials.clear()
    obj.data.materials.append(mat)
    WR.skin(obj, src, limb, limb_blend(g, V), gap, edges_of(F))
    edge = np.min([fields[n][0] for n in EDGE_NAMES[kind] if n in fields], axis=0)
    edge_group(obj, edge)
    thick = 1 - D._smooth(edge, 0.004, 0.011)
    base_t, hem_t = THICKNESS[name]
    WR.make_shell(obj, base_t * (1 - thick) + hem_t * thick)
    g.extra["n_shell"] = len(obj.data.vertices)
    # loose threads: the tee's sleeve hems only (at the body hems they would hang over the cord
    # belt, at the trouser hems into the boots); the drawstring on the trousers
    pr = g.extra["params"]
    if not pr.get("threads", True):
        acc_fields = {}
    elif kind == "tee":
        acc_fields = {"hem": fields["cuff"]}
    elif kind == "trousers":
        acc_fields = {k: v for k, v in fields.items() if k != "leghem"}
    else:
        acc_fields = {}
    drawstring = kind == "trousers" and pr.get("drawstring", True)
    parts = R.accessories(obj, acc_fields, V, rng, drawstring=drawstring) if (acc_fields or drawstring) else []
    if eye is not None:
        parts += WR.lacing(obj, eye)
    join_parts(obj, parts, src)
    g.extra["edge_final"] = read_group(obj, "_edge", 0.05)
    attach(obj, arm)
    me = obj.data
    me.calc_loop_triangles()
    loft = dict(cloth_mm=round(1000 * (base_t * (1 - thick) + hem_t * thick).mean(), 2),
                air_gap_mm_median=round(1000 * float(np.median(gap)), 2), air_gap_mm_mean=round(1000 * float(np.mean(gap)), 2))
    info = dict(vertices=len(me.vertices), triangles=len(me.loop_triangles),
                bones_weighted=len(obj.vertex_groups), accessories=len(parts), texel_uv_per_m=uvpm,
                textures={k: Path(v).name for k, v in paths.items()}, texture_stats=stats, loft=loft)
    if kind == "trousers":
        below = V[:, 2] < g.extra["params"]["knee_z"] - 0.04
        outer = gap + base_t * (1 - thick) + hem_t * thick
        info["below_knee_outer_mm"] = dict(max=round(1000 * float(outer[below].max()), 2),
                                           p99=round(1000 * float(np.percentile(outer[below], 99)), 2),
                                           mean=round(1000 * float(outer[below].mean()), 2))
    log(f"{name}: built {info['vertices']} verts, {info['triangles']} tris, {info['bones_weighted']} bones, loft {loft}")
    return info


def build_coat(name, g, V, F, obj, body, layers, src, limb, arm, rng):
    p = g.extra["params"]
    short = name.replace("SKM_", "")
    V, fields, gap = detail(g, V, F, obj, body, layers)
    n0 = len(V)
    W = WR.skin(obj, src, limb, limb_blend(g, V), gap, edges_of(F), iters=6)
    del W
    reg, ax = g.extra["region"], g.extra["axial"]
    trim = np.zeros(n0)
    trim[reg == 3] = 1.0
    for side, r in (("l", 1), ("r", 2)):
        m = reg == r
        s_end = g.extra["sleeves"][side]["s_end"]
        trim[m] = np.maximum(trim[m], D._smooth(ax[m] - (s_end - p["cuff"]), -0.004, 0.006))
    if "opening" in fields:
        d_open = fields["opening"][0]
        trim = np.maximum(trim, 1 - D._smooth(d_open, p["facing"] - 0.006, p["facing"] + 0.004))
    t = THICKNESS[name][0] + (THICKNESS[name][1] - THICKNESS[name][0]) * trim
    for side in ("l", "r"):
        A = V[g.extra["sleeves"][side]["under"][0]]
        prox = np.exp(-(np.linalg.norm(V - A, axis=1) / 0.06) ** 2)
        t *= 1 - 0.6 * prox
    # the fleece packs down where the arm rests against the body: thinner down the side seams
    # and on the inside of the sleeves, so arms can come closer to the sides
    yc = np.array([body.center_y(z) for z in np.clip(V[:, 2], 0.9, 1.6)])
    th = np.degrees(np.arctan2(V[:, 0], -(V[:, 1] - yc)))
    under = np.exp(-((np.abs(th) - 90.0) / 22.0) ** 2) * D._smooth(V[:, 2], 1.06, 1.20) * (reg == 0)
    Nn = WR.smooth_normals(V, F)
    for side, r, sg in (("l", 1, 1.0), ("r", 2, -1.0)):
        m = reg == r
        under[m] = np.clip(-Nn[m, 0] * sg, 0, 1) ** 1.5
    t *= 1 - 0.45 * under
    edge = np.min([fields[n][0] for n in EDGE_NAMES["coat"] if n in fields], axis=0)
    edge_group(obj, edge)
    seams0 = {tuple(sorted(e.vertices)) for e in obj.data.edges if e.use_seam}
    N, Vo = WR.make_shell(obj, t)
    me = obj.data
    Va = np.array([v.co for v in me.vertices])
    assert len(Va) == 2 * n0, (len(Va), n0)
    inner_idx = np.arange(n0)
    outer_idx = np.arange(n0, 2 * n0)
    og = np.concatenate([inner_idx, inner_idx])
    is_outer = np.arange(2 * n0) >= n0
    lofts = np.linalg.norm(Va[outer_idx] - Va[inner_idx], axis=1)
    log(f"{name}: shell built, loft mm mean {1000 * lofts.mean():.1f} min {1000 * lofts.min():.1f} "
        f"max {1000 * lofts.max():.1f}")
    trim_all = trim[og]
    # the fleece turned out at collar, cuffs and front edges bunches into locks
    dirn = N
    bumps = CT.fleece_bumps(V, SEED + 5)
    Va[outer_idx] += dirn * (0.0055 * trim * bumps - 0.0012 * trim)[:, None]
    set_verts(obj, Va)
    fields_all = {k: (d[og], a[og]) for k, (d, a) in fields.items()}
    shellc = is_outer.astype(np.float64)
    seams = seams0 | {(a + n0, b + n0) for a, b in seams0}
    uvpm, face_shell = CT.unwrap_coat(obj, is_outer, extra_seams=seams)
    tdir = gdir(name) / "Textures"
    tdir.mkdir(parents=True, exist_ok=True)
    cached = WORK / f"tex_{short}.json"
    if REUSE["tex"] and cached.exists():
        prev = json.loads(cached.read_text())
        paths = {k: Path(v) for k, v in prev["paths"].items()}
        stats = prev["stats"]
        log(f"{name}: reusing textures")
    else:
        paths, stats = CT.compose_coat(obj, fields_all, trim_all, shellc, face_shell, uvpm, tdir, short, R=4096,
                                       seed=SEED, log=log)
        cached.write_text(json.dumps(dict(paths={k: str(v) for k, v in paths.items()}, stats=stats)))
    mat = make_material("M_" + short, paths)
    obj.data.materials.clear()
    obj.data.materials.append(mat)
    parts = WR.toggles(obj, g.extra["opening"], V)
    join_parts(obj, parts, src)
    g.extra["edge_final"] = read_group(obj, "_edge", 0.05)
    attach(obj, arm)
    g.extra["inner_idx"] = inner_idx
    g.extra["loft_inner"] = lofts
    me = obj.data
    me.calc_loop_triangles()
    loft = dict(loft_mm_mean=round(1000 * float(lofts.mean()), 1), loft_mm_body=round(1000 * float(lofts[trim < 0.1].mean()), 1),
                loft_mm_trims=round(1000 * float(lofts[trim > 0.9].mean()), 1) if (trim > 0.9).any() else None,
                air_gap_to_skin_mm_median=round(1000 * float(np.median(gap)), 1))
    info = dict(vertices=len(me.vertices), triangles=len(me.loop_triangles), bones_weighted=len(obj.vertex_groups),
                accessories=len(parts), texel_uv_per_m=uvpm, textures={k: Path(v).name for k, v in paths.items()},
                texture_stats=stats, loft=loft)
    log(f"{name}: built {info['vertices']} verts, {info['triangles']} tris, loft {loft}")
    return info


def base_materials(base):
    for name, obj in base.items():
        short = name.replace("SKM_", "")
        paths = {k: BASE_TEX / f"T_{short}_{k}.png" for k in ("basecolor", "normal", "roughness", "ao")}
        mat = make_material("M_" + short + "_Review", paths)
        obj.data.materials.clear()
        obj.data.materials.append(mat)


def test_poses(arm, body, body_obj, garments, base, fitted):
    face_V = body.V[body.n_body:]
    face_N = body.N[body.n_body:]
    face_T = body.T[(body.T >= body.n_body).all(1)] - body.n_body
    rest_z = {n: np.array([v.co.z for v in o.data.vertices]) for n, o in garments.items()}
    metrics = {}
    for pose in WR.POSES:
        WR.apply_pose(arm, pose)
        surf = WR.posed_surface(arm, body_obj, face_V, face_N, face_T)
        m = {}
        for n, o in garments.items():
            m[n] = R.poke_metrics(o, surf, fitted[n][0].extra["edge_final"])
        lay = {}
        for top in ("SKM_LinenTee", "SKM_LinenLongShirt"):
            for under in ("SKM_PrimitiveShorts", "SKM_WoolTrousers"):
                inner = base.get(under) or garments.get(under)
                lay[f"{top} over {under}"] = WR.layer_poke(garments[top], inner, surf, mask=rest_z[top] < 1.16)
        coat = garments["SKM_FurCoat"]
        gc = fitted["SKM_FurCoat"][0]
        for top in ("SKM_LinenTee", "SKM_LinenLongShirt"):
            lay[f"SKM_FurCoat over {top}"] = WR.layer_poke(coat, garments[top], surf, idx=gc.extra["inner_idx"],
                                                           loft=gc.extra["loft_inner"])
        m["layers"] = lay
        metrics[pose] = m
        log(f"pose {pose}: " + ", ".join(f"{k.replace('SKM_', '')} {v['inside_pct']:.2f}% (max {v['max_depth_mm']:.1f} mm)"
                                         for k, v in m.items() if k != "layers"))
        log("   layers: " + ", ".join(f"{k.replace('SKM_', '')} {v['inside_pct']:.2f}%"
                                      + (f" / through {v['through_outer_pct']:.2f}%" if "through_outer_pct" in v else "")
                                      for k, v in lay.items()))
    R.reset_pose(arm)
    return metrics


def build(args, arm, body_obj, face_obj, body, base, fitted, objs):
    REUSE["tex"] = args.reuse_textures
    rng = np.random.default_rng(SEED)
    src = R.weight_source(body_obj, face_obj, arm)
    limb = WR.limb_sources(src)
    shorts_layer = mesh_layer(base["SKM_PrimitiveShorts"], body.all)
    info = {}
    done = {}
    for name in ORDER:
        g, V, F = fitted[name]
        obj = objs[name]
        if name == "SKM_WoolTrousers":
            layers = []
        elif name == "SKM_FurCoat":
            layers = [(shorts_layer, 0.0035), (mesh_layer(done["SKM_WoolTrousers"], body.all), 0.0035),
                      (mesh_layer(done["SKM_LinenTee"], body.all), 0.0040),
                      (mesh_layer(done["SKM_LinenLongShirt"], body.all), 0.0040)]
        else:
            layers = [(shorts_layer, 0.0030), (mesh_layer(done["SKM_WoolTrousers"], body.all), 0.0030)]
        builder = build_coat if name == "SKM_FurCoat" else build_cloth
        info[name] = builder(name, g, V, F, obj, body, layers, src, limb, arm, rng)
        done[name] = obj
    for o in list(limb.values()) + [src]:
        me = o.data
        bpy.data.objects.remove(o)
        bpy.data.meshes.remove(me)
    info["detail_maps"] = {k: v.name for k, v in WT.wool_detail(gdir("SKM_WoolTrousers") / "Textures", SEED).items()}
    bind = {n: R.poke_metrics(o, body.all, fitted[n][0].extra["edge_final"]) for n, o in done.items()}
    log(f"bind pose: {bind}")
    poses = test_poses(arm, body, body_obj, done, base, fitted)
    exports, coverage = {}, {}
    for name, obj in done.items():
        d = gdir(name)
        n, bones = R.export_fbx(d / f"{name}.fbx", arm, [obj], log=log)
        exports[name] = dict(file=f"{d.name}/{name}.fbx", bones=n, bone_names=bones)
        mask = d / f"BodyCoverageMask_{name.replace('SKM_', '')}.png"
        cov, _ = R.coverage_mask(body_obj, [obj], {name: fitted[name][0].extra["edge_final"]}, mask, margin=0.012,
                                 max_dist=0.08 if name == "SKM_FurCoat" else 0.04, z_min=0.0)
        cov["file"] = f"{d.name}/{mask.name}"
        coverage[name] = cov
        log(f"{name}: coverage {cov['covered_triangles']} / {cov['total_triangles']} triangles")
    report = dict(recipe="Scripts/Blender/Recipes/clothing_wardrobe.py", seed=SEED, blender=bpy.app.version_string,
                  inputs={p.name: sha256(p) for p in (BODY_FBX, FACE_FBX, SHORTS_FBX, BELT_JSON)},
                  landmarks=body.lm, params={n: {k: v for k, v in fitted[n][0].extra["params"].items()
                                                 if isinstance(v, (int, float, str, bool))} for n in done},
                  garments=info, bind_pose=bind, test_poses=poses, exports=exports, coverage=coverage,
                  export_settings=dict(units="centimeters (FBX UnitScaleFactor 1.0, raw cm values like the UE export)",
                                       axes="Z up, -Y forward (FBX UpAxis Z, FrontAxis -Y), same as input",
                                       armature="object 'root' exported as the root bone above pelvis",
                                       leaf_bones=False, animation=False, deform_only=True, smoothing="FACE",
                                       tangents=True, normal_maps="OpenGL (+Y): flip green in Unreal"))
    report["pouch_clearance"] = pouch_clearance(done["SKM_WoolTrousers"])
    report["belt_clearance"] = belt_clearance(done, fitted)
    report["warmth"] = WARMTH
    files = {}
    for name in done:
        d = gdir(name)
        for pth in sorted(d.rglob("*.*")):
            files[str(pth.relative_to(OUT)).replace("\\", "/")] = sha256(pth)
    report["files"] = files
    (OUT / "report.json").write_text(json.dumps(report, indent=1, default=float) + "\n")
    Rn.prepare_face(face_obj, bpy.data.objects["FaceRig"], arm)
    Rn.assign_review_materials(body_obj, face_obj)
    base_materials(base)
    for o in list(bpy.data.objects):
        if o.name == "PreviewCam":
            bpy.data.objects.remove(o)
    bpy.ops.wm.save_as_mainfile(filepath=str(BLEND), relative_remap=True)
    log(f"saved {BLEND}")


def pouch_clearance(trousers):
    """How close the trousers come to the forage pouch where it lies on her right hip (the pouch
    was fitted over the shorts)."""
    try:
        fit = json.loads(POUCH_FIT.read_text())
        before = set(bpy.data.objects)
        bpy.ops.import_scene.fbx(filepath=str(POUCH_FBX))
        new = [o for o in bpy.data.objects if o not in before]
        mesh = next(o for o in new if o.type == "MESH")
        F0 = 0.040
        pivot = np.array(min(fit["belt"], key=lambda q: abs(-q[1] - F0)))
        V0, N, T = B.mesh_arrays(mesh)
        # the prop's own frame: pick the axis convention that puts it on her right hip
        best = None
        for sx, sy in ((1, 1), (1, -1), (-1, -1), (-1, 1)):
            V = V0 * np.array([sx, sy, 1.0]) + pivot
            err = np.linalg.norm(V.mean(0) - np.array([-0.17, -0.03, 0.89]))
            if best is None or err < best[0]:
                best = (err, V, (sx, sy))
        err, V, flip = best
        tV, tN, tT = B.mesh_arrays(trousers)
        ts = B.Surface(tV, tN, tT)
        s, _, _ = ts.signed(V)
        for o in new:
            bpy.data.objects.remove(o)
        return dict(pouch_vertices_inside_trousers=int((s < 0).sum()), min_signed_mm=round(1000 * float(s.min()), 2),
                    placement_error_m=round(float(err), 3), axis_flip=flip,
                    note="pouch placed at its belt pivot; positive = clear of the trousers' outer surface")
    except Exception as exc:  # the pouch is optional context
        return dict(error=str(exc))


def belt_clearance(done, fitted):
    belt = Tp.Belt(json.loads(BELT_JSON.read_text()))
    out = {}
    for name in ("SKM_LinenTee", "SKM_LinenLongShirt", "SKM_FurCoat"):
        o = done[name]
        n_shell = fitted[name][0].extra.get("n_shell") or 2 * len(fitted[name][0].extra["inner_idx"])
        V = np.array([v.co for v in o.data.vertices])[:n_shell]
        lo = []
        for t in range(-180, 180, 10):
            tr = math.radians(t)
            d = np.array([math.sin(tr), -math.cos(tr)])
            sel = ((V[:, :2] @ d) > 0.97 * np.linalg.norm(V[:, :2], axis=1)) & (np.abs(V[:, 0]) < 0.19) & (V[:, 2] < 1.3)
            if sel.any():
                lo.append(float(V[sel, 2].min() - (belt.z(t) + belt.radius)))
        out[name] = dict(min_hem_above_belt_top_mm=round(1000 * min(lo), 1) if lo else None)
    return out


def sha256(path):
    import hashlib
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


REUSE = {"tex": False}

# Suggested relative warmth (0-10 game scale) from the built insulation: cloth thickness, trapped
# air and coverage (see the loft numbers per garment), with rough clo equivalents.
WARMTH = {
    "scale": "0-10, relative; rough clo equivalents from typical garment tables",
    "ranking": ["SKM_FurCoat", "SKM_WoolTrousers", "SKM_LinenLongShirt", "SKM_LinenTee"],
    "SKM_FurCoat": dict(suggested=6.5, clo=1.0, why="~18 mm fleece loft (24 mm at trims), windproof skin, collar and "
                                                    "closed cuffs, insulates when damp; hip length"),
    "SKM_WoolTrousers": dict(suggested=2.0, clo=0.28, why="1.9 mm fulled wool + ~5 mm trapped air, full legs, warm when wet"),
    "SKM_LinenLongShirt": dict(suggested=1.0, clo=0.2, why="1 mm linen, fitted (4.5 mm air gap), long sleeves, cuffs"),
    "SKM_LinenTee": dict(suggested=0.5, clo=0.1, why="1.2 mm linen, short sleeves, fitted (3.7 mm air gap)"),
}


# ====================================================================== render

REVIEW = {
    # name: (visible garments, target, camera dir, distance, lens, resolution, f-stop)
    "tee_front": (("SKM_LinenTee", "SKM_PrimitiveShorts"), (0, -0.02, 1.12), (0, -1, 0.06), 2.7, 70, (2160, 3840), None),
    "tee_three_quarter": (("SKM_LinenTee", "SKM_PrimitiveShorts"), (0, -0.02, 1.12), (-0.8, -1, 0.1), 2.7, 70, (2160, 3840), None),
    "tee_back": (("SKM_LinenTee", "SKM_PrimitiveShorts"), (0, 0.02, 1.12), (0, 1, 0.06), 2.7, 70, (2160, 3840), None),
    "longshirt_front": (("SKM_LinenLongShirt", "SKM_WoolTrousers"), (0, -0.02, 0.95), (0, -1, 0.05), 3.4, 70, (2160, 3840), None),
    "longshirt_three_quarter": (("SKM_LinenLongShirt", "SKM_WoolTrousers"), (0, -0.02, 0.95), (0.8, -1, 0.08), 3.4, 70, (2160, 3840), None),
    "trousers_back": (("SKM_WoolTrousers", "SKM_PrimitiveTankTop"), (0, 0.02, 0.62), (0.35, 1, 0.05), 2.6, 70, (2160, 3840), None),
    "trousers_side": (("SKM_WoolTrousers", "SKM_PrimitiveTankTop"), (0, 0.0, 0.62), (1, -0.1, 0.05), 2.6, 70, (2160, 3840), None),
    "layered_front": (("SKM_FurCoat", "SKM_LinenLongShirt", "SKM_WoolTrousers"), (0, -0.02, 0.95), (0, -1, 0.05), 3.4, 70, (2160, 3840), None),
    "layered_three_quarter": (("SKM_FurCoat", "SKM_LinenLongShirt", "SKM_WoolTrousers"), (0, -0.02, 0.95), (-0.8, -1, 0.1), 3.4, 70, (2160, 3840), None),
    "layered_back": (("SKM_FurCoat", "SKM_LinenLongShirt", "SKM_WoolTrousers"), (0, 0.02, 0.95), (0, 1, 0.06), 3.4, 70, (2160, 3840), None),
    "layered_side": (("SKM_FurCoat", "SKM_LinenLongShirt", "SKM_WoolTrousers"), (0, 0.0, 0.95), (1, -0.08, 0.06), 3.4, 70, (2160, 3840), None),
    "detail_coat_collar": (("SKM_FurCoat", "SKM_LinenLongShirt", "SKM_WoolTrousers"), (0.02, -0.12, 1.33), (-0.35, -1, 0.15), 0.85, 85, (3840, 2160), 8),
    "detail_coat_cuff": (("SKM_FurCoat", "SKM_LinenLongShirt", "SKM_WoolTrousers"), (0.43, -0.12, 1.06), (-0.2, -1, 0.25), 0.55, 85, (3840, 2160), 8),
    "detail_shirt_lacing": (("SKM_LinenLongShirt", "SKM_WoolTrousers"), (0.0, -0.13, 1.39), (-0.25, -1, 0.12), 0.55, 85, (3840, 2160), 8),
    "detail_trousers_knee": (("SKM_WoolTrousers", "SKM_PrimitiveTankTop"), (0.07, -0.08, 0.45), (-0.35, -1, 0.1), 0.85, 85, (3840, 2160), 8),
    "detail_tee": (("SKM_LinenTee", "SKM_PrimitiveShorts"), (-0.12, -0.08, 1.30), (0.35, -1, 0.12), 0.75, 85, (3840, 2160), 8),
}
POSE_OUTFITS = {"layered": ("SKM_FurCoat", "SKM_LinenLongShirt", "SKM_WoolTrousers"),
                "tee": ("SKM_LinenTee", "SKM_WoolTrousers")}
ALL_GARMENTS = ("SKM_LinenTee", "SKM_LinenLongShirt", "SKM_WoolTrousers", "SKM_FurCoat",
                "SKM_PrimitiveTankTop", "SKM_PrimitiveShorts")


def show_only(names):
    for n in ALL_GARMENTS:
        o = bpy.data.objects.get(n)
        if o:
            o.hide_render = n not in names


def render_stage(args):
    bpy.ops.wm.open_mainfile(filepath=str(BLEND))
    RENDERS.mkdir(parents=True, exist_ok=True)
    backend = Rn.setup_scene(HDRI, args.samples)
    log(f"render device {backend}")
    arm = bpy.data.objects["root"]
    body_obj = bpy.data.objects["SKM_MHC_Heroine_BodyMesh"]
    face = bpy.data.objects["SKM_MHC_Heroine_FaceMesh"]
    want = set(args.only or [])
    R.reset_pose(arm)
    for name, (vis, tgt, d, dist, lens, res, fstop) in REVIEW.items():
        if want and name not in want:
            continue
        show_only(vis)
        Rn.shoot(RENDERS / f"{name}.png", tgt, d, dist, lens, res, fstop)
        log(f"rendered {name}")
    for outfit, vis in POSE_OUTFITS.items():
        for pose in WR.POSES:
            tag = f"pose_{outfit}_{pose}"
            if want and tag not in want and pose not in want:
                continue
            show_only(vis)
            WR.apply_pose(arm, pose)
            objs = [body_obj, face] + [bpy.data.objects[n] for n in vis]
            R.ground(arm, objs)
            V = np.vstack([B.mesh_arrays(o)[0] for o in [body_obj, face]])
            lo, hi = V.min(0), V.max(0)
            c = (lo + hi) / 2
            size = float(np.max(hi - lo))
            Rn.shoot(RENDERS / f"{tag}.png", tuple(c), (-0.8, -1, 0.18), 1.55 * size + 1.2, 55, (2160, 3840), None)
            log(f"rendered {tag}")
    R.reset_pose(arm)


if __name__ == "__main__":
    main()
