"""Homestead: five pairs of skinned footwear for the MetaHuman heroine, fitted in Blender.

* ``SKM_FurBoots``: sheepskin winter boots, hair side in, fur cuff turned out, suede outside,
  a gathered thick hide sole, leather thongs wrapped round the ankle and the shaft.
* ``SKM_WovenSandals``: twined plant-fibre sandals with a corded rim, a toe cord, side and heel
  loops and ankle ties knotted in front.
* ``SKM_TurnShoes``: soft low-cut vegetable-tanned turnshoes laced over the instep with a thong.
* ``SKM_Sneakers``: slim low-top canvas sneakers on a vulcanised gum sole with foxing and a toe cap.
* ``SKM_AnkleBoots``: flat, close-fitting cognac calf lace-up ankle boots on a welted sole.

Reproducible, seeded Blender 5.2 build. Run headless from the repo root:

    & "C:\\Program Files\\Blender Foundation\\Blender 5.2\\blender.exe" --background --factory-startup `
        --python Scripts\\Blender\\Recipes\\footwear.py -- --stage all

Stages: ``fit`` (geometry + Workbench previews only), ``build`` (geometry, UVs, textures,
weights, test poses, FBX, coverage masks, .blend), ``render`` (4K Cycles review renders from the
saved .blend), ``all``. ``--only FurBoots TurnShoes`` limits the pairs.

Inputs (outside the repo): the heroine's un-culled MetaHuman body
``SKM_MHC_Heroine_BodyMesh_Full.fbx`` (and the face, for full-figure review renders) on
``metahuman_base_skel``; the primitive outfit .blend is appended into review renders for
context. Outputs go to Assets/Characters/Footwear/<Name>/.

Construction research is summarised in ``shoemaking/pairs.py`` and ``shoemaking/modern.py``; the parametric foot last in
``shoemaking/last.py``; the procedural leather, fur and fibre maps in ``shoemaking/leather.py``.

PROVENANCE: all footwear geometry and textures are original and generated by this script.
Review renders use the CC0 Poly Haven HDRI "Kloofendal 48d Partly Cloudy (Pure Sky)"
(render lighting only, not shipped with the asset).
"""
import argparse
import hashlib
import json
import math
import sys
import time
from pathlib import Path

import bpy
import numpy as np

HERE = Path(__file__).resolve()
sys.path.insert(0, str(HERE.parent))

from outfit import body as B  # noqa: E402
from shoemaking import geo as G  # noqa: E402
from shoemaking import modern as MD  # noqa: E402
from shoemaking import pairs as PR  # noqa: E402

ROOT = HERE.parents[3]
INPUT_DIR = Path(r"E:\Repos\HomesteadShared\MetaHumanBody")
BODY_FBX = INPUT_DIR / "SKM_MHC_Heroine_BodyMesh_Full.fbx"
FACE_FBX = INPUT_DIR / "SKM_MHC_Heroine_FaceMesh.fbx"
OUTFIT_BLEND = ROOT / "Assets" / "Characters" / "PrimitiveOutfit" / "PrimitiveOutfit.blend"
OUT = ROOT / "Assets" / "Characters" / "Footwear"
HDRI = ROOT / "Assets" / "Source" / "Blender" / "polyhaven" / "kloofendal_48d_partly_cloudy_puresky_2k.exr"
SEED = 20260927
TEX_SIZE = 2048
PAIRS = ("FurBoots", "WovenSandals", "TurnShoes", "Sneakers", "AnkleBoots")
T0 = time.time()


def log(msg):
    print(f"[footwear {time.time() - T0:7.1f}s] {msg}", flush=True)


def sha256(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def load_body():
    arm, meshes = B.import_skeletal(BODY_FBX)
    arm.name = "root"
    body_obj = meshes[0]
    body_obj.name = "SKM_MHC_Heroine_BodyMesh"
    V, N, T = B.mesh_arrays(body_obj)
    bones = {b.name: (np.array(arm.matrix_world @ b.head_local), np.array(arm.matrix_world @ b.tail_local))
             for b in arm.data.bones}
    return arm, body_obj, (V, N, T), bones


def build_geometry(name, V, N, T, bones):
    surf = B.Surface(V, N, T)
    if name == "FurBoots":
        built = PR.fur_boots(V, T, surf, log=log, seed=SEED)
    elif name == "TurnShoes":
        built = PR.turnshoes(V, T, surf, log=log, seed=SEED)
    elif name == "Sneakers":
        built = MD.sneakers(V, T, surf, log=log, seed=SEED)
    elif name == "AnkleBoots":
        built = MD.ankle_boots(V, T, surf, log=log, seed=SEED)
    else:
        built = PR.woven_sandals(V, T, surf, bones, log=log, seed=SEED)
    obj = built.mb.build(built.name)
    built.obj = obj
    me = obj.data
    me.calc_loop_triangles()
    log(f"{built.name}: {len(me.vertices)} verts, {len(me.loop_triangles)} tris")
    return built


def preview(objs, body_obj, path, focus=(0.0, -0.05, 0.13), scale=0.62):
    sc = bpy.context.scene
    sc.render.engine = "BLENDER_WORKBENCH"
    sc.display.shading.light = "STUDIO"
    sc.display.shading.color_type = "OBJECT"
    sc.display.shading.show_backface_culling = True
    sc.render.resolution_x, sc.render.resolution_y = 1600, 1100
    body_obj.color = (0.75, 0.55, 0.45, 1)
    for o in objs:
        o.color = (0.42, 0.31, 0.2, 1)
    from mathutils import Vector
    cd = bpy.data.cameras.new("PreviewCam")
    cam = bpy.data.objects.new("PreviewCam", cd)
    sc.collection.objects.link(cam)
    sc.camera = cam
    cd.type = "ORTHO"
    cd.ortho_scale = scale
    tgt = Vector(focus)
    for view, d in (("front", (0, -1, 0.05)), ("side", (1, 0, 0.05)), ("medial", (-1, 0.3, 0.2)),
                    ("back", (0, 1, 0.1)), ("tq", (0.8, -1, 0.55)), ("top", (0.0, -0.15, 1)),
                    ("bottom", (0.05, -0.1, -1))):
        cam.location = tgt + Vector(d).normalized() * 3
        cam.rotation_euler = (tgt - cam.location).to_track_quat("-Z", "Y").to_euler()
        sc.render.filepath = str(path).replace(".png", f"_{view}.png")
        bpy.ops.render.render(write_still=True)
    bpy.data.objects.remove(cam)


def main():
    argv = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
    ap = argparse.ArgumentParser()
    ap.add_argument("--stage", default="all", choices=["fit", "build", "render", "all"])
    ap.add_argument("--only", nargs="*", default=list(PAIRS))
    ap.add_argument("--samples", type=int, default=160)
    ap.add_argument("--views", nargs="*", help="render only these view names")
    args = ap.parse_args(argv)
    np.random.seed(SEED)
    if args.stage == "render":
        from shoemaking import stages as FS
        for name in args.only:
            FS.render_stage(name, args)
        return
    for name in args.only:
        bpy.ops.wm.read_factory_settings(use_empty=True)
        arm, body_obj, (V, N, T), bones = load_body()
        built = build_geometry(name, V, N, T, bones)
        work = OUT / name / "_work"
        work.mkdir(parents=True, exist_ok=True)
        if args.stage == "fit":
            preview([built.obj], body_obj, work / "fit.png")
            bpy.ops.wm.save_as_mainfile(filepath=str(work / "fit.blend"))
            continue
        from shoemaking import stages as FS
        FS.finish_build(name, built, arm, body_obj, (V, N, T), bones, args)
        if args.stage == "all":
            FS.render_stage(name, args)


if __name__ == "__main__":
    main()
