"""Homestead: a modern wardrobe for the heroine, fitted as closely as her starter tank top and shorts.

    SKM_ScoopTank     black 1x1 rib-knit tank: deep scoop front and back, slim straps, hem above the navel
    SKM_CropTop       crimson jersey crop top: wide scoop neck, cap sleeves, cut well above the navel
    SKM_SkinnyJeans   mid-blue stretch-denim skinny jeans: low rise, back pockets, J-stitched fly, ankle length
    SKM_SkinnyJeansDark  the same jeans in a dark-rinse indigo (Jenny wanted both washes)
    SKM_Leggings      charcoal heather knit leggings: mid rise elastic band, skin-tight to the ankle
    SKM_BikerJacket   black pebbled-leather cropped jacket: stand collar, centre zip, zipped cuffs, ends at the waist

Jenny (2026-10-09): "a variety of modern-looking clothes - never mind the time period", all
"fitted, sexy, attractive, and/or revealing, similar to the original clothes". Each garment sits
2.0-3.0 mm off the skin like the starter outfit (3.2 mm); the jacket over a top, 5.5 mm.

Reproducible, seeded Blender 5.2 build (headless), from the repo root:

    & "C:\\Program Files\\Blender Foundation\\Blender 5.2\\blender.exe" --background --factory-startup `
        --python Scripts\\Blender\\Recipes\\modern_wardrobe.py -- --stage all

Stages: ``fit`` (fitted meshes + Workbench previews in _work), ``build`` (fit, folds, UVs, textures,
weights, thickness, test poses, FBX, coverage masks, report, .blend), ``render`` (4K Cycles review
renders), ``all``. It reuses ``clothing_wardrobe.py`` (fit solve, cloth build) and the shared
``outfit`` modules; the knit, denim and leather fabrics live in ``outfit/wardrobe_tex.py``.

Inputs: the coordinator's Unreal exports of the heroine's body and face
(``E:\\Repos\\HomesteadShared\\MetaHumanBody``) and the starter shorts/tank FBXs.
Outputs: ``Assets/Characters/ModernClothing/<Garment>/`` plus shared renders, report and .blend.

PROVENANCE: all garment geometry and textures are original and generated by this script (numpy
procedural maps). Review renders use the CC0 Poly Haven HDRI "Kloofendal 48d Partly Cloudy
(Pure Sky)" for lighting only.
"""
import argparse
import json
import sys
import time
from pathlib import Path

import bpy
import numpy as np

HERE = Path(__file__).resolve()
sys.path.insert(0, str(HERE.parent))

import clothing_wardrobe as CW  # noqa: E402
from outfit import body as B  # noqa: E402
from outfit import garments as G  # noqa: E402
from outfit import layers as Ly  # noqa: E402
from outfit import render as Rn  # noqa: E402
from outfit import rig as R  # noqa: E402
from outfit import wardrobe_rig as WR  # noqa: E402
from outfit import wardrobe_tex as WT  # noqa: E402

ROOT = HERE.parents[3]
OUT = ROOT / "Assets" / "Characters" / "ModernClothing"
WORK = OUT / "_work"
RENDERS = OUT / "Renders"
BLEND = OUT / "ModernClothing.blend"
SEED = 20261009
BOTTOMS = ("SKM_SkinnyJeans", "SKM_SkinnyJeansDark", "SKM_Leggings")
LAYER_BOTTOMS = ("SKM_SkinnyJeans", "SKM_Leggings")  # the dark wash shares the mid-blue cut exactly
TOPS = ("SKM_ScoopTank", "SKM_CropTop")
JACKET = "SKM_BikerJacket"
ORDER = BOTTOMS + TOPS + (JACKET,)
THICKNESS = {  # cloth (m): base, at hems/edges
    "SKM_ScoopTank": (0.0008, 0.0016),
    "SKM_CropTop": (0.0008, 0.0017),
    "SKM_SkinnyJeans": (0.0015, 0.0030),
    "SKM_SkinnyJeansDark": (0.0015, 0.0030),
    "SKM_Leggings": (0.0009, 0.0018),
    "SKM_BikerJacket": (0.0020, 0.0036),
}
KNIT_SEAMS = {"side": ("felled", 0.5, [0.2]), "shoulder": ("felled", 0.5, [0.2]), "armhole": ("felled", 0.5, [0.2])}
STYLES = {
    "SKM_ScoopTank": dict(
        fabric="knit", rib=True, base=(0.020, 0.020, 0.023), thread=(0.03, 0.03, 0.035), warp=9.0, weft=12.0,
        streak=0.0, fade=0.0, rough=0.84, seams={"hem": ("cover", 1.2, [0.3, 0.9]), "neck": ("bind", 0.7, [0.45]),
                                                 **KNIT_SEAMS}, grime={}, yellow=0.0, dust=0.0),
    "SKM_CropTop": dict(
        fabric="knit", base=(0.190, 0.014, 0.024), thread=(0.17, 0.014, 0.022), warp=11.0, weft=14.0,
        streak=0.0, fade=0.0, rough=0.86, seams={"hem": ("cover", 1.0, [0.3, 0.8]), "cuff": ("cover", 0.9, [0.3, 0.7]),
                                                 "neck": ("bind", 0.7, [0.45]), **KNIT_SEAMS},
        grime={}, yellow=0.0, dust=0.0),
    "SKM_Leggings": dict(
        fabric="knit", base=(0.052, 0.052, 0.058), thread=(0.05, 0.05, 0.055), warp=13.0, weft=16.0, heather=0.35,
        streak=0.0, fade=0.0, rough=0.82, seams={"waist": ("band", 4.0, []), "leghem": ("cover", 1.0, [0.3, 0.8]),
                                                 "side": ("felled", 0.5, [0.15]), "inseam": ("felled", 0.5, [0.15]),
                                                 "crotch": ("felled", 0.5, [0.15])},
        grime={}, yellow=0.0, dust=0.0),
    "SKM_SkinnyJeans": dict(
        fabric="denim", base=(0.020, 0.042, 0.115), weft_col=(0.40, 0.40, 0.38), weft_mix=0.18, thread=(0.52, 0.36, 0.11), macro=0.12,
        warp=12.0, weft=9.0, streak=0.0, fade=0.0, fade_denim=0.40, faded=(0.08, 0.14, 0.28),
        seams={"waist": ("band", 3.6, [0.25, 0.55, 3.35]), "leghem": ("turn", 1.6, [1.2]),
               "side": ("felled", 0.9, [0.2, 0.75]), "inseam": ("felled", 0.9, [0.2, 0.75]),
               "crotch": ("felled", 0.9, [0.2, 0.75])},
        pockets=((0.072, 0.905, 0.060, 0.065), (-0.072, 0.905, 0.060, 0.065)), fly=(0.985, 0.885, 0.032),
        grime={}, yellow=0.0, dust=0.0, rough_clip=(0.78, 0.95)),
    "SKM_BikerJacket": dict(
        fabric="leather", base=(0.016, 0.015, 0.014), thread=(0.03, 0.03, 0.03), grain=7.0, rough=0.52, macro=0.04,
        streak=0.0, fade=0.0, warp=1.0, weft=1.0,
        seams={"hem": ("band", 1.2, [0.5]), "cuff": ("band", 0.9, [0.4]), "collartop": ("bind", 0.6, [0.4]),
               "opening": ("zip", 0.22, [0.9]), "cuffseam": ("felled", 0.5, [0.3]),
               "side": ("felled", 0.9, [0.3, 0.7]), "shoulder": ("felled", 0.9, [0.3, 0.7]),
               "armhole": ("felled", 0.9, [0.3]), "collarseam": ("felled", 0.6, [0.3])},
        metal=(0.30, 0.29, 0.28), grime={}, yellow=0.0, dust=0.0, rough_clip=(0.40, 0.78)),
}


DENIM = STYLES["SKM_SkinnyJeans"]
STYLES["SKM_SkinnyJeansDark"] = dict(DENIM, base=(0.009, 0.014, 0.040), weft_col=(0.18, 0.18, 0.20), weft_mix=0.10,
                                     fade_denim=0.15, faded=(0.03, 0.05, 0.11))


def log(msg):
    print(f"[modern {time.time() - T0:7.1f}s] {msg}", flush=True)


T0 = time.time()


def fitted_params(body):
    """The heroine's fit and cut for each garment, as overrides of the shared outfit params."""
    lm = body.lm
    jz, navel = lm["jugular_z"], lm["navel"][2]
    flat = lambda z: {int(t): z for t in range(-180, 181)}  # noqa: E731
    over = {
        "SKM_SkinnyJeans": dict(name="SKM_SkinnyJeans", waist_front_z=navel - 0.105, waist_back_rise=0.045,
                                offset=0.0026, crotch_ease=0.0030, thigh_ease=0.0, knee_patch=False,
                                drawstring=False, threads=False, waist_gather=0.0, fold_scale=0.6),
        "SKM_SkinnyJeansDark": None,
        "SKM_Leggings": dict(name="SKM_Leggings", waist_front_z=navel - 0.045, waist_back_rise=0.035,
                             offset=0.0020, crotch_ease=0.0012, thigh_ease=0.0, knee_patch=False,
                             drawstring=False, threads=False, waist_gather=0.3, fold_scale=0.3,
                             hem_z=float(body.bones["foot_l"][0][2]) + 0.012),
        "SKM_CropTop": dict(name="SKM_CropTop", base=0.0025, hang=0.0, sleeve_ease=0.0025, sleeve_end=0.100,
                            x_in=0.080, zc=jz - 0.105, z_in=jz - 0.016, zcb=jz - 0.010, z_inb=jz + 0.020,
                            hem=flat(navel + 0.060), fold_amp=0.0008, sleeve_fold=0.0006, threads=False),
        "SKM_BikerJacket": dict(name="SKM_BikerJacket", base=0.0055, hang=0.0, sleeve_ease=0.0055, cuff=0.035,
                                cuff_ease=0.0035, hem=flat(navel + 0.020), hem_gap=0.0,
                                collar=dict(rows=2, dz=0.009, lean=-0.002, off=0.0035),
                                open_gap=0.0012, facing=0.02, fold_amp=0.0014, sleeve_fold=0.0012, threads=False),
    }
    over["SKM_SkinnyJeansDark"] = dict(over["SKM_SkinnyJeans"], name="SKM_SkinnyJeansDark")
    return over


def fit_tank(body):
    p = G.tank_top_params(body)
    p.update(hem_z=body.lm["navel"][2] - 0.022, scoop_z=body.lm["apex"][2] - 0.005,
             strap_w=0.012, offset=0.0025)
    p["bscoop_z"] = p["bs_z"] - 0.085
    g = G.build_tank_top(body, p)
    g.name = "SKM_ScoopTank"
    V, F = g.arrays()
    F = CW.orient_out(V, F, body.all)
    loops = G.boundary_loops(F, len(V))
    fixed = np.zeros(len(V), bool)
    for lp in loops:
        fixed[lp] = True
    surfs, labels = G.surface_labels(g, V, body)
    off = np.full(len(V), p["offset"])
    V, gap = G.relax(V, F, fixed, G.MultiSurface(surfs, labels), off, log=log)
    p.update(kind="tank", name=g.name, fold_amp=0.0006, threads=False)
    n = len(V)
    g.extra.update(params=p, region=np.zeros(n, np.int64), axial=np.zeros(n), hem_axis=np.zeros((n, 3)),
                   sleeves={}, neck_loop=[], loops=loops, gap=gap, offsets=off,
                   constraints=[(Ly.ClosedSurface(body.all), off, None)])
    log(f"{g.name}: {n} verts, gap mm min {1000 * gap.min():.2f} median {1000 * np.median(gap):.2f}")
    return g, V, F


def fit_all(body, belt, shorts_obj):
    over = fitted_params(body)
    prof = Ly.RadialProfile(body, 0.98, 1.36)
    shorts_layer = CW.mesh_layer(shorts_obj, body.all)
    out = {}
    CW.LEG_DRAPE_K = 0.0
    for name in BOTTOMS:
        CW.FITTED["trousers"] = over[name]
        out[name] = CW.fit_trousers(body, [])
    under = [(shorts_layer, 0.0030)] + [(CW.shell_layer(V, F, THICKNESS[n][0], n), 0.0030)
                                        for n, (g, V, F) in out.items() if n in LAYER_BOTTOMS]
    out["SKM_ScoopTank"] = fit_tank(body)
    CW.FITTED["tee"] = over["SKM_CropTop"]
    out["SKM_CropTop"] = CW.fit_top(body, "tee", belt, under, prof)
    jacket_layers = [(lay, 0.0035) for lay, _ in under]
    for name in TOPS:
        g, V, F = out[name]
        jacket_layers.append((CW.shell_layer(V, F, THICKNESS[name][0], name), 0.0035))
    CW.FITTED["coat"] = over[JACKET]
    out[JACKET] = CW.fit_top(body, "coat", belt, jacket_layers, prof)
    return out


def configure_cw():
    """Point the shared wardrobe build at this wardrobe's outputs, thicknesses and fabrics."""
    CW.OUT, CW.WORK, CW.SEED = OUT, WORK, SEED
    CW.THICKNESS.update(THICKNESS)
    WT.STYLES.update(STYLES)


def layers_for(name, done, shorts_layer, body):
    if name in BOTTOMS:
        return []
    low = [(shorts_layer, 0.0030)] + [(CW.mesh_layer(done[n], body.all), 0.0030) for n in LAYER_BOTTOMS]
    if name in TOPS:
        return low
    return [(lay, 0.0035) for lay, _ in low] + [(CW.mesh_layer(done[n], body.all), 0.0035) for n in TOPS]


def test_poses(arm, body_obj, garments, fitted):
    face_V = CW_body.V[CW_body.n_body:]
    face_N = CW_body.N[CW_body.n_body:]
    face_T = CW_body.T[(CW_body.T >= CW_body.n_body).all(1)] - CW_body.n_body
    metrics = {}
    for pose in WR.POSES:
        WR.apply_pose(arm, pose)
        surf = WR.posed_surface(arm, body_obj, face_V, face_N, face_T)
        m = {n: R.poke_metrics(o, surf, fitted[n][0].extra["edge_final"]) for n, o in garments.items()}
        m["layers"] = {f"{JACKET} over {t}": WR.layer_poke(garments[JACKET], garments[t], surf) for t in TOPS}
        metrics[pose] = m
        log(f"pose {pose}: " + ", ".join(f"{k.replace('SKM_', '')} {v['inside_pct']:.2f}% (max {v['max_depth_mm']:.1f} mm)"
                                         for k, v in m.items() if k != "layers"))
        log("   layers: " + ", ".join(f"{k.replace('SKM_', '')} {v['inside_pct']:.2f}%" for k, v in m["layers"].items()))
    R.reset_pose(arm)
    return metrics


def build(args, arm, body_obj, face_obj, body, base, fitted, objs):
    CW.REUSE["tex"] = args.reuse_textures
    rng = np.random.default_rng(SEED)
    src = R.weight_source(body_obj, face_obj, arm)
    limb = WR.limb_sources(src)
    shorts_layer = CW.mesh_layer(base["SKM_PrimitiveShorts"], body.all)
    info, done = {}, {}
    for name in ORDER:
        g, V, F = fitted[name]
        info[name] = CW.build_cloth(name, g, V, F, objs[name], body, layers_for(name, done, shorts_layer, body),
                                    src, limb, arm, rng)
        done[name] = objs[name]
    for o in list(limb.values()) + [src]:
        me = o.data
        bpy.data.objects.remove(o)
        bpy.data.meshes.remove(me)
    bind = {n: R.poke_metrics(o, body.all, fitted[n][0].extra["edge_final"]) for n, o in done.items()}
    log(f"bind pose: {bind}")
    poses = test_poses(arm, body_obj, done, fitted)
    exports, coverage = {}, {}
    for name, obj in done.items():
        d = CW.gdir(name)
        n, bones = R.export_fbx(d / f"{name}.fbx", arm, [obj], log=log)
        exports[name] = dict(file=f"{d.name}/{name}.fbx", bones=n, bone_names=bones)
        mask = d / f"BodyCoverageMask_{name.replace('SKM_', '')}.png"
        cov, _ = R.coverage_mask(body_obj, [obj], {name: fitted[name][0].extra["edge_final"]}, mask, margin=0.012,
                                 max_dist=0.06 if name == JACKET else 0.04, z_min=0.0)
        cov["file"] = f"{d.name}/{mask.name}"
        coverage[name] = cov
        log(f"{name}: coverage {cov['covered_triangles']} / {cov['total_triangles']} triangles")
    report = dict(recipe="Scripts/Blender/Recipes/modern_wardrobe.py", seed=SEED, blender=bpy.app.version_string,
                  inputs={p.name: CW.sha256(p) for p in (CW.BODY_FBX, CW.FACE_FBX, CW.SHORTS_FBX)},
                  params={n: {k: v for k, v in fitted[n][0].extra["params"].items()
                              if isinstance(v, (int, float, str, bool))} for n in done},
                  garments=info, bind_pose=bind, test_poses=poses, exports=exports, coverage=coverage,
                  export_settings=dict(units="centimeters (FBX UnitScaleFactor 1.0)", axes="Z up, -Y forward",
                                       armature="object 'root' exported as the root bone above pelvis",
                                       leaf_bones=False, animation=False, deform_only=True,
                                       normal_maps="OpenGL (+Y): flip green in Unreal"))
    files = {}
    for name in done:
        for pth in sorted(CW.gdir(name).rglob("*.*")):
            files[str(pth.relative_to(OUT)).replace("\\", "/")] = CW.sha256(pth)
    report["files"] = files
    (OUT / "report.json").write_text(json.dumps(report, indent=1, default=float) + "\n")
    Rn.prepare_face(face_obj, bpy.data.objects["FaceRig"], arm)
    Rn.assign_review_materials(body_obj, face_obj)
    for o in list(bpy.data.objects):
        if o.name == "PreviewCam":
            bpy.data.objects.remove(o)
    bpy.ops.wm.save_as_mainfile(filepath=str(BLEND), relative_remap=True)
    log(f"saved {BLEND}")


# ====================================================================== render

REVIEW = {
    # name: (visible garments, target, camera dir, distance, lens, resolution, f-stop)
    "tank_jeans_front": (("SKM_ScoopTank", "SKM_SkinnyJeans"), (0, -0.02, 0.95), (0, -1, 0.05), 3.4, 70, (2160, 3840), None),
    "tank_jeans_three_quarter": (("SKM_ScoopTank", "SKM_SkinnyJeans"), (0, -0.02, 0.95), (-0.8, -1, 0.1), 3.4, 70, (2160, 3840), None),
    "jeans_back": (("SKM_SkinnyJeans", "SKM_ScoopTank"), (0, 0.02, 0.62), (0.35, 1, 0.05), 2.6, 70, (2160, 3840), None),
    "crop_leggings_front": (("SKM_CropTop", "SKM_Leggings"), (0, -0.02, 0.95), (0, -1, 0.05), 3.4, 70, (2160, 3840), None),
    "crop_leggings_side": (("SKM_CropTop", "SKM_Leggings"), (0, 0.0, 0.95), (1, -0.1, 0.05), 3.4, 70, (2160, 3840), None),
    "leggings_back": (("SKM_Leggings", "SKM_CropTop"), (0, 0.02, 0.62), (-0.35, 1, 0.05), 2.6, 70, (2160, 3840), None),
    "jacket_front": ((JACKET, "SKM_ScoopTank", "SKM_SkinnyJeans"), (0, -0.02, 0.95), (0, -1, 0.05), 3.4, 70, (2160, 3840), None),
    "jacket_three_quarter": ((JACKET, "SKM_CropTop", "SKM_SkinnyJeans"), (0, -0.02, 0.95), (0.8, -1, 0.1), 3.4, 70, (2160, 3840), None),
    "jacket_back": ((JACKET, "SKM_ScoopTank", "SKM_SkinnyJeans"), (0, 0.02, 0.95), (0, 1, 0.06), 3.4, 70, (2160, 3840), None),
    "detail_jacket_zip": ((JACKET, "SKM_ScoopTank", "SKM_SkinnyJeans"), (0.0, -0.12, 1.25), (-0.3, -1, 0.15), 0.75, 85, (3840, 2160), 8),
    "dark_jeans_front": (("SKM_CropTop", "SKM_SkinnyJeansDark"), (0, -0.02, 0.95), (0, -1, 0.05), 3.4, 70, (2160, 3840), None),
    "dark_jeans_back": (("SKM_SkinnyJeansDark", "SKM_CropTop"), (0, 0.02, 0.62), (-0.35, 1, 0.05), 2.6, 70, (2160, 3840), None),
    "detail_jeans_pocket": (("SKM_SkinnyJeans", "SKM_ScoopTank"), (0.06, 0.09, 0.88), (0.3, 1, 0.1), 0.7, 85, (3840, 2160), 8),
    "detail_tank_neck": (("SKM_ScoopTank", "SKM_SkinnyJeans"), (0.0, -0.11, 1.30), (0.3, -1, 0.12), 0.65, 85, (3840, 2160), 8),
}
ALL = ORDER + ("SKM_PrimitiveTankTop", "SKM_PrimitiveShorts")


def show_only(names):
    for n in ALL:
        o = bpy.data.objects.get(n)
        if o:
            o.hide_render = n not in names


def render_stage(args):
    bpy.ops.wm.open_mainfile(filepath=str(BLEND))
    RENDERS.mkdir(parents=True, exist_ok=True)
    log(f"render device {Rn.setup_scene(CW.HDRI, args.samples)}")
    arm = bpy.data.objects["root"]
    body_obj = bpy.data.objects["SKM_MHC_Heroine_BodyMesh"]
    face = bpy.data.objects["SKM_MHC_Heroine_FaceMesh"]
    want = set(args.only or [])
    R.reset_pose(arm)
    for name, (vis, tgt, d, dist, lens, res, fstop) in REVIEW.items():
        if want and name not in want:
            continue
        show_only(vis)
        Rn.shoot(RENDERS / f"{name}.png", tgt, d, dist, lens, res, fstop)
        log(f"rendered {name}")
    for outfit, vis in (("jacket", (JACKET, "SKM_CropTop", "SKM_SkinnyJeans")), ("tank", ("SKM_ScoopTank", "SKM_Leggings"))):
        for pose in ("walk", "felling_swing", "squat"):
            tag = f"pose_{outfit}_{pose}"
            if want and tag not in want and pose not in want:
                continue
            show_only(vis)
            WR.apply_pose(arm, pose)
            objs = [body_obj, face] + [bpy.data.objects[n] for n in vis]
            R.ground(arm, objs)
            V = np.vstack([B.mesh_arrays(o)[0] for o in [body_obj, face]])
            lo, hi = V.min(0), V.max(0)
            Rn.shoot(RENDERS / f"{tag}.png", tuple((lo + hi) / 2), (-0.8, -1, 0.18), 1.55 * float(np.max(hi - lo)) + 1.2,
                     55, (2160, 3840), None)
            log(f"rendered {tag}")
    R.reset_pose(arm)


CW_body = None


def main():
    global CW_body
    argv = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
    ap = argparse.ArgumentParser()
    ap.add_argument("--stage", default="all", choices=["fit", "build", "render", "all"])
    ap.add_argument("--samples", type=int, default=128)
    ap.add_argument("--reuse-textures", action="store_true")
    ap.add_argument("--only", nargs="*")
    args = ap.parse_args(argv)
    configure_cw()
    if args.stage == "render":
        render_stage(args)
        return
    np.random.seed(SEED)
    WORK.mkdir(parents=True, exist_ok=True)
    arm, body_obj, face_obj, body, base, belt = CW.load_inputs()
    CW_body = body
    fitted = fit_all(body, belt, base["SKM_PrimitiveShorts"])
    objs = {}
    for name, (g, V, F) in fitted.items():
        obj, F2 = CW.garment_object(g, V, F, body)
        fitted[name] = (g, V, F2)
        objs[name] = obj
    if args.stage == "fit":
        CW.COLORS.update({"SKM_ScoopTank": (0.08, 0.08, 0.09, 1), "SKM_CropTop": (0.6, 0.08, 0.1, 1),
                          "SKM_SkinnyJeans": (0.15, 0.22, 0.45, 1), "SKM_SkinnyJeansDark": (0.05, 0.07, 0.15, 1), "SKM_Leggings": (0.2, 0.2, 0.22, 1),
                          "SKM_BikerJacket": (0.05, 0.05, 0.05, 1)})
        for name in objs:
            CW.preview({name}, WORK / f"fit_{name}.png")
        CW.preview({JACKET, "SKM_CropTop", "SKM_SkinnyJeans"}, WORK / "fit_layered.png")
        bpy.ops.wm.save_as_mainfile(filepath=str(WORK / "fit.blend"))
        return
    CW.base_materials(base)
    build(args, arm, body_obj, face_obj, body, base, fitted, objs)
    if args.stage == "all":
        render_stage(args)


if __name__ == "__main__":
    main()
