"""Homestead: makeshift homespun outfit for the MetaHuman heroine (cropped tank top + low-rise shorts).

Reproducible, seeded Blender 5.2 build. Run headless from the repo root:

    & "C:\\Program Files\\Blender Foundation\\Blender 5.2\\blender.exe" --background --factory-startup `
        --python Scripts\\Blender\\Recipes\\primitive_outfit.py -- --stage all

Stages: ``build`` (fit, detail, UVs, textures, weights, export, coverage mask, .blend),
``render`` (4K Cycles beauty + test-pose renders from the saved .blend), ``all`` (both).
``--preview`` writes quick Workbench fit previews instead of the Cycles renders.

Inputs (exported from Unreal, outside the repo): the heroine's un-culled MetaHuman body
``SKM_MHC_Heroine_BodyMesh_Full.fbx`` and face ``SKM_MHC_Heroine_FaceMesh.fbx`` on
``metahuman_base_skel`` (cm, Z up, -Y forward). Outputs go to Assets/Characters/PrimitiveOutfit.

Garment research notes (what we are imitating): pre-industrial homespun linen/hemp or cotton
is a plain (tabby) weave of hand-spun yarn, roughly 8-12 threads/cm, with slubs (thick, soft
spots) and uneven thread spacing; undyed linen is a grey-cream to oatmeal colour that yellows
and greys with wear. Garments are sewn from flat pattern pieces with running or back stitches
(~3-4 stitches/cm by hand), seams pressed to one side, and edges finished by a narrow rolled or
double-turned hem, bias binding, or a folded casing for a drawstring. Woven cloth barely
stretches, so it tents over the bust apex and bridges hollows instead of clinging like knit,
creases sharply and gathers where a drawstring cinches it.

PROVENANCE: all garment geometry and textures are original and generated by this script
(numpy procedural weave/stain/seam maps). Review renders use the CC0 Poly Haven HDRI
"Kloofendal 48d Partly Cloudy (Pure Sky)" (render lighting only, not shipped with the asset).
"""
import argparse
import json
import sys
import time
from pathlib import Path

import bpy
import numpy as np

HERE = Path(__file__).resolve()
sys.path.insert(0, str(HERE.parent))

from outfit import body as B  # noqa: E402
from outfit import cloth as C  # noqa: E402
from outfit import detail as D  # noqa: E402
from outfit import garments as G  # noqa: E402
from outfit import render as Rn  # noqa: E402
from outfit import rig as R  # noqa: E402

ROOT = HERE.parents[3]
INPUT_DIR = Path(r"E:\Repos\HomesteadShared\MetaHumanBody")
BODY_FBX = INPUT_DIR / "SKM_MHC_Heroine_BodyMesh_Full.fbx"
FACE_FBX = INPUT_DIR / "SKM_MHC_Heroine_FaceMesh.fbx"
OUT = ROOT / "Assets" / "Characters" / "PrimitiveOutfit"
TEX = OUT / "Textures"
RENDERS = OUT / "Renders"
WORK = OUT / "_work"
BLEND = OUT / "PrimitiveOutfit.blend"
HDRI = ROOT / "Assets" / "Source" / "Blender" / "polyhaven" / "kloofendal_48d_partly_cloudy_puresky_2k.exr"
SEED = 20260926
TEX_SIZE = 4096
REUSE_TEX = False
T0 = time.time()


def log(msg):
    print(f"[outfit {time.time() - T0:7.1f}s] {msg}", flush=True)


def link(obj, coll=None):
    (coll or bpy.context.scene.collection).objects.link(obj)
    return obj


def garment_object(g, V, F, body):
    """Create the Blender mesh for a fitted garment with outward-facing quads."""
    import bmesh
    me = bpy.data.meshes.new(g.name)
    me.from_pydata(V.tolist(), [], F.tolist())
    me.update()
    bm = bmesh.new()
    bm.from_mesh(me)
    bm.faces.ensure_lookup_table()
    cent = np.array([f.calc_center_median() for f in bm.faces])
    nrm = np.array([f.normal for f in bm.faces])
    _, loc, bn = body.all.signed(cent)
    flip = [bm.faces[i] for i in np.where((nrm * bn).sum(1) < 0)[0]]
    if flip:
        bmesh.ops.reverse_faces(bm, faces=flip)
    bm.to_mesh(me)
    bm.free()
    me.shade_smooth()
    panel = me.attributes.new("panel", "INT", "FACE")
    panel.data.foreach_set("value", np.array(g.face_panel, np.int32))
    for e in me.edges:
        a, b = sorted(e.vertices)
        e.use_seam = (a, b) in g.uv_seams
    obj = link(bpy.data.objects.new(g.name, me))
    return obj


def fit(body):
    out = {}
    for build in (G.build_tank_top, G.build_shorts):
        g = build(body)
        V, F = g.arrays()
        loops = G.boundary_loops(F, len(V))
        fixed = np.zeros(len(V), bool)
        for lp in loops:
            fixed[lp] = True
        log(f"{g.name}: {len(V)} verts, {len(F)} quads, {len(loops)} boundary loops {[len(l) for l in loops]}")
        surfs, labels = G.surface_labels(g, V, body)
        V, gap = G.relax(V, F, fixed, G.MultiSurface(surfs, labels), G.offsets(g, V, body), log=log)
        g.extra["labels"] = labels
        for lp in loops:
            P = V[lp]
            d = np.linalg.norm(np.diff(np.vstack([P, P[:1]]), axis=0), axis=1)
            log(f"  boundary loop {len(lp)}: z {P[:, 2].min():.3f}-{P[:, 2].max():.3f}, longest edge {1000 * d.max():.1f} mm")
        g.extra["gap"] = gap
        g.extra["loops"] = loops
        out[g.name] = (g, V, F)
    return out


def preview(objs, body_obj, path, views=(("front", (0, -4, 1.1), (90, 0, 0)),
                                         ("side", (4, 0, 1.1), (90, 0, 90)),
                                         ("back", (0, 4, 1.1), (90, 0, 180)))):
    import math
    sc = bpy.context.scene
    sc.render.engine = "BLENDER_WORKBENCH"
    sc.display.shading.light = "STUDIO"
    sc.display.shading.color_type = "OBJECT"
    sc.render.resolution_x, sc.render.resolution_y = 900, 1100
    for o in bpy.context.scene.objects:
        if o.type == "MESH" and o not in objs:
            o.color = (0.75, 0.55, 0.45, 1)
    for o in objs:
        o.color = (0.9, 0.9, 0.85, 1) if "Tank" in o.name else (0.7, 0.6, 0.45, 1)
    cam = bpy.data.objects.get("PreviewCam") or link(bpy.data.objects.new("PreviewCam", bpy.data.cameras.new("PreviewCam")))
    cam.data.type = "ORTHO"
    cam.data.ortho_scale = 0.95
    sc.camera = cam
    for name, loc, rot in views:
        cam.location = loc
        cam.rotation_euler = [math.radians(a) for a in rot]
        sc.render.filepath = str(path).replace(".png", f"_{name}.png")
        bpy.ops.render.render(write_still=True)


def main():
    argv = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
    ap = argparse.ArgumentParser()
    ap.add_argument("--stage", default="all", choices=["build", "render", "all", "fit", "tex"])
    ap.add_argument("--samples", type=int, default=192)
    ap.add_argument("--reuse-textures", action="store_true", help="skip texture synthesis if cached (iteration)")
    ap.add_argument("--only", nargs="*", help="render only these view names")
    args = ap.parse_args(argv)
    global REUSE_TEX
    REUSE_TEX = args.reuse_textures
    if args.stage == "render":
        render_stage(args)
        return
    np.random.seed(SEED)
    WORK.mkdir(parents=True, exist_ok=True)
    bpy.ops.wm.read_factory_settings(use_empty=True)
    arm, meshes = B.import_skeletal(BODY_FBX)
    arm.name = "root"
    body_obj = meshes[0]
    body_obj.name = "SKM_MHC_Heroine_BodyMesh"
    face_arm, face_meshes = B.import_skeletal(FACE_FBX)
    face_arm.name = "FaceRig"
    face_obj = face_meshes[0]
    face_obj.name = "SKM_MHC_Heroine_FaceMesh"
    log(f"face mesh: {len(face_obj.data.vertices)} verts, materials {[m.name for m in face_obj.data.materials if m]}")
    body = B.Body(arm, body_obj, extra=[face_obj])
    log("landmarks " + json.dumps({k: (np.round(v, 4).tolist() if isinstance(v, list) else round(v, 4))
                                  for k, v in body.lm.items()}))
    fitted = fit(body)
    objs = []
    for name, (g, V, F) in fitted.items():
        obj = garment_object(g, V, F, body)
        objs.append(obj)
        log(f"{name}: gap mm min {1000 * g.extra['gap'].min():.2f} median {1000 * np.median(g.extra['gap']):.2f}"
            f" max {1000 * g.extra['gap'].max():.2f}")
    if args.stage == "fit":
        preview(objs, body_obj, WORK / "fit.png")
        bpy.ops.wm.save_as_mainfile(filepath=str(WORK / "fit.blend"))
        return
    finish_build(args, arm, body, body_obj, face_obj, fitted, objs)
    if args.stage == "all":
        render_stage(args)


BEAUTY_VIEWS = {
    # name: (target, camera direction, distance, lens, resolution, f-stop)
    "front": ((0, -0.02, 1.12), (0, -1, 0.06), 2.7, 70, (2160, 3840), None),
    "back": ((0, 0.02, 1.12), (0, 1, 0.06), 2.7, 70, (2160, 3840), None),
    "three_quarter": ((0, -0.02, 1.12), (-0.8, -1, 0.1), 2.7, 70, (2160, 3840), None),
    "side": ((0, -0.02, 1.12), (1, -0.08, 0.06), 2.7, 70, (2160, 3840), None),
    "detail_midriff": ((0.03, -0.12, 1.115), (-0.35, -1, 0.10), 1.05, 85, (3840, 2160), 8),
    "detail_back": ((0.0, 0.07, 1.02), (0.45, 1, 0.18), 0.8, 85, (3840, 2160), 8),
    "detail_strap": ((0.08, -0.03, 1.38), (-0.55, -1, 0.35), 0.62, 85, (3840, 2160), 8),
    "detail_hem": ((0.09, -0.08, 0.84), (-0.5, -1, -0.05), 0.6, 85, (3840, 2160), 8),
}


def render_stage(args):
    bpy.ops.wm.open_mainfile(filepath=str(BLEND))
    RENDERS.mkdir(parents=True, exist_ok=True)
    backend = Rn.setup_scene(HDRI, args.samples)
    log(f"render device {backend}")
    arm = bpy.data.objects["root"]
    body_obj = bpy.data.objects["SKM_MHC_Heroine_BodyMesh"]
    garments = [bpy.data.objects[n] for n in ("SKM_PrimitiveTankTop", "SKM_PrimitiveShorts")]
    face = bpy.data.objects["SKM_MHC_Heroine_FaceMesh"]
    want = set(args.only or [])
    done = []
    R.reset_pose(arm)
    for name, (tgt, d, dist, lens, res, fstop) in BEAUTY_VIEWS.items():
        if want and name not in want:
            continue
        done.append(Rn.shoot(RENDERS / f"beauty_{name}.png", tgt, d, dist, lens, res, fstop))
        log(f"rendered {name}")
    for pose in R.POSES:
        if want and pose not in want:
            continue
        R.apply_pose(arm, pose)
        R.ground(arm, [body_obj, face] + garments)
        V = np.vstack([B.mesh_arrays(o)[0] for o in [body_obj, face]])
        lo, hi = V.min(0), V.max(0)
        c = (lo + hi) / 2
        size = float(np.max(hi - lo))
        done.append(Rn.shoot(RENDERS / f"pose_{pose}.png", tuple(c), (-0.8, -1, 0.18), 1.55 * size + 1.2, 55,
                             (2160, 3840), None))
        log(f"rendered pose {pose}")
    R.reset_pose(arm)
    return done


def make_material(name, paths):
    mat = bpy.data.materials.new(name)
    if mat.node_tree is None:
        mat.use_nodes = True
    nt = mat.node_tree
    bsdf = nt.nodes["Principled BSDF"]

    def tex(path, srgb):
        node = nt.nodes.new("ShaderNodeTexImage")
        node.image = bpy.data.images.load(str(path), check_existing=True)
        node.image.colorspace_settings.name = "sRGB" if srgb else "Non-Color"
        return node

    base, ao = tex(paths["basecolor"], True), tex(paths["ao"], False)
    mix = nt.nodes.new("ShaderNodeMix")
    mix.data_type = "RGBA"
    mix.blend_type = "MULTIPLY"
    mix.inputs["Factor"].default_value = 0.6
    nt.links.new(base.outputs["Color"], mix.inputs["A"])
    nt.links.new(ao.outputs["Color"], mix.inputs["B"])
    nt.links.new(mix.outputs["Result"], bsdf.inputs["Base Color"])
    rough = tex(paths["roughness"], False)
    nt.links.new(rough.outputs["Color"], bsdf.inputs["Roughness"])
    nrm = tex(paths["normal"], False)
    nmap = nt.nodes.new("ShaderNodeNormalMap")
    nt.links.new(nrm.outputs["Color"], nmap.inputs["Color"])
    nt.links.new(nmap.outputs["Normal"], bsdf.inputs["Normal"])
    bsdf.inputs["Specular IOR Level"].default_value = 0.35
    bsdf.inputs["Sheen Weight"].default_value = 0.0
    return mat


def detail_and_texture(body, fitted, objs):
    TEX.mkdir(parents=True, exist_ok=True)
    info = {}
    for obj in objs:
        g, V, F = fitted[obj.name]
        surfs, labels = G.surface_labels(g, V, body)
        surf = G.MultiSurface(surfs, labels)
        off = G.offsets(g, V, body)
        fields = D.feature_fields(g, V, g.extra["loops"])
        h = D.wrinkles(g, V, fields, body, SEED)
        _, _, nrm = surf.signed(V)
        V2, gap = D.collide(V + nrm * h[:, None], surf, off)
        for i, v in enumerate(obj.data.vertices):
            v.co = V2[i]
        obj.data.update()
        fitted[obj.name] = (g, V2, F)
        g.extra["gap"] = gap
        g.extra["fields"] = fields
        uvpm = D.unwrap(obj)
        short = obj.name.replace("SKM_", "")
        cached = WORK / "tex_info.json"
        if REUSE_TEX and cached.exists() and obj.name in json.loads(cached.read_text()):
            prev = json.loads(cached.read_text())[obj.name]
            paths = {k: TEX / v for k, v in prev["textures"].items()}
            stats = {k: v for k, v in prev.items() if k not in ("textures", "texel_uv_per_m")}
            log(f"{obj.name}: reusing cached textures")
        else:
            paths, stats = C.compose(obj, fields, uvpm, TEX, short, R=TEX_SIZE, seed=SEED, log=log)
        mat = make_material("M_" + short, paths)
        obj.data.materials.clear()
        obj.data.materials.append(mat)
        info[obj.name] = dict(texel_uv_per_m=uvpm, textures={k: p.name for k, p in paths.items()}, **stats)
        log(f"{obj.name}: textures {stats}")
    info["detail"] = {k: p.name for k, p in C.detail_weave(TEX, SEED).items()}
    return info


EDGE_FIELDS = {"SKM_PrimitiveTankTop": ("hem", "bind"), "SKM_PrimitiveShorts": ("waist", "leghem")}


def rig_garments(arm, body, body_obj, face_obj, fitted, objs):
    src = R.weight_source(body_obj, face_obj, arm)
    rng = np.random.default_rng(SEED)
    info = {}
    for obj in objs:
        g, V, F = fitted[obj.name]
        fields = g.extra["fields"]
        edge = np.min([fields[n][0] for n in EDGE_FIELDS[obj.name]], axis=0)
        R.transfer_weights(obj, src)
        names, W = R.read_weights(obj)
        gap = g.extra["gap"]
        alpha = np.clip((gap - 0.006) / 0.02, 0.05, 0.5)
        W = R.clean_weights(W, alpha, G.edges_of(F), iters=3)
        R.write_weights(obj, names, W)
        vg = obj.vertex_groups.new(name="_edge")
        for i, d in enumerate(edge):
            vg.add([i], float(np.clip(d / 0.05, 0, 1)), "REPLACE")
        thick = 1 - D._smooth(edge, 0.004, 0.011)
        R.solidify(obj, thick)
        parts = R.accessories(obj, fields, V, rng, drawstring="Shorts" in obj.name)
        for p in parts:
            R.transfer_weights(p, src)
            pn, pw = R.read_weights(p)
            R.write_weights(p, pn, R.clean_weights(pw))
            p.data.materials.append(obj.data.materials[0])
        bpy.ops.object.select_all(action="DESELECT")
        for p in parts:
            p.select_set(True)
        obj.select_set(True)
        bpy.context.view_layer.objects.active = obj
        bpy.ops.object.join()
        eg = obj.vertex_groups["_edge"]
        e = np.zeros(len(obj.data.vertices))
        for v in obj.data.vertices:
            for gg in v.groups:
                if gg.group == eg.index:
                    e[v.index] = gg.weight * 0.05
        obj.vertex_groups.remove(eg)
        g.extra["edge_final"] = e
        mod = obj.modifiers.new("Armature", "ARMATURE")
        mod.object = arm
        obj.parent = arm
        names = [vg.name for vg in obj.vertex_groups]
        me = obj.data
        me.calc_loop_triangles()
        info[obj.name] = dict(vertices=len(me.vertices), triangles=len(me.loop_triangles),
                              bones_weighted=len(names), accessories=len(parts))
        log(f"{obj.name}: rigged, {len(me.vertices)} verts, {len(me.loop_triangles)} tris, {len(names)} weighted bones")
    bpy.data.objects.remove(src)
    return info


def test_poses(arm, body, body_obj, objs, fitted):
    metrics = {}
    face_V = body.V[body.n_body:]
    face_N = body.N[body.n_body:]
    face_T = body.T[(body.T >= body.n_body).all(1)] - body.n_body
    for pose in R.POSES:
        R.apply_pose(arm, pose)
        V, N, Tr = B.mesh_arrays(body_obj)
        hb = arm.pose.bones["head"]
        M = np.array(arm.matrix_world @ hb.matrix @ hb.bone.matrix_local.inverted())
        fV = face_V @ M[:3, :3].T + M[:3, 3]
        fN = face_N @ M[:3, :3].T
        surf = B.Surface(np.vstack([V, fV]), np.vstack([N, fN]), np.vstack([Tr, face_T + len(V)]))
        metrics[pose] = {o.name: R.poke_metrics(o, surf, fitted[o.name][0].extra["edge_final"]) for o in objs}
        log(f"pose {pose}: " + ", ".join(f"{k}: {v['inside_pct']:.2f}% inside ({v['inside_near_edge']} near edges),"
                                         f" max {v['max_depth_mm']:.1f} mm" for k, v in metrics[pose].items()))
    R.reset_pose(arm)
    return metrics


def finish_build(args, arm, body, body_obj, face_obj, fitted, objs):
    tex_info = detail_and_texture(body, fitted, objs)
    (WORK / "tex_info.json").write_text(json.dumps(tex_info, indent=1, default=str))
    if args.stage == "tex":
        bpy.ops.wm.save_as_mainfile(filepath=str(WORK / "textured.blend"))
        return
    rig_info = rig_garments(arm, body, body_obj, face_obj, fitted, objs)
    bind = {}
    for o in objs:
        bind[o.name] = R.poke_metrics(o, body.all, fitted[o.name][0].extra["edge_final"])
    log(f"bind pose: {bind}")
    pose_metrics = test_poses(arm, body, body_obj, objs, fitted)
    exports = {}
    for o in objs:
        n, bones = R.export_fbx(OUT / f"{o.name}.fbx", arm, [o], log=log)
        exports[o.name] = dict(file=f"{o.name}.fbx", bones=n, bone_names=bones)
    combo = [o.copy() for o in objs]
    for c, o in zip(combo, objs):
        c.data = o.data.copy()
        link(c)
    bpy.ops.object.select_all(action="DESELECT")
    for c in combo:
        c.select_set(True)
    bpy.context.view_layer.objects.active = combo[0]
    bpy.ops.object.join()
    outfit = bpy.context.view_layer.objects.active
    outfit.name = outfit.data.name = "SKM_PrimitiveOutfit"
    n, bones = R.export_fbx(OUT / "SKM_PrimitiveOutfit.fbx", arm, [outfit], log=log)
    exports["SKM_PrimitiveOutfit"] = dict(file="SKM_PrimitiveOutfit.fbx", bones=n, bone_names=bones)
    bpy.data.objects.remove(outfit)
    cov_info, _ = R.coverage_mask(body_obj, objs, {o.name: fitted[o.name][0].extra["edge_final"] for o in objs},
                                  OUT / "BodyCoverageMask.png")
    log(f"coverage: {cov_info}")
    report = dict(recipe="Scripts/Blender/Recipes/primitive_outfit.py", seed=SEED, blender=bpy.app.version_string,
                  inputs={p.name: sha256(p) for p in (BODY_FBX, FACE_FBX)}, landmarks=body.lm,
                  params={o.name: fitted[o.name][0].extra["params"] for o in objs},
                  garments=rig_info, textures=tex_info, bind_pose=bind, test_poses=pose_metrics,
                  exports=exports, coverage=cov_info,
                  export_settings=dict(units="centimeters (FBX UnitScaleFactor 1.0, raw cm values like the UE export)",
                                       axes="Z up, -Y forward (FBX UpAxis Z, FrontAxis -Y), same as input",
                                       armature="object 'root' exported as the root bone above pelvis",
                                       leaf_bones=False, animation=False, deform_only=True,
                                       smoothing="FACE", tangents=True))
    report["files"] = {p.name: sha256(p) for p in sorted(OUT.glob("*.fbx"))}
    report["files"].update({f"Textures/{p.name}": sha256(p) for p in sorted(TEX.glob("*.png"))})
    report["files"]["BodyCoverageMask.png"] = sha256(OUT / "BodyCoverageMask.png")
    (OUT / "report.json").write_text(json.dumps(report, indent=1, default=float) + "\n")
    Rn.prepare_face(face_obj, bpy.data.objects["FaceRig"], arm)
    Rn.assign_review_materials(body_obj, face_obj)
    for o in list(bpy.data.objects):
        if o.name == "PreviewCam":
            bpy.data.objects.remove(o)
    bpy.ops.wm.save_as_mainfile(filepath=str(BLEND), relative_remap=True)
    log(f"saved {BLEND}")


def sha256(path):
    import hashlib
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


if __name__ == "__main__":
    main()
