"""Build the estate's rain and overcast assets inside the running editor (add-rain-weather).

Run with PIE stopped:
  pyfile Scripts/Terrain/build_weather.py            (McpHelpers)
First run `python Scripts/prepare_rain_loop.py` so Assets/Audio/Ambience/RainLoop.wav exists.

Writes /Game/SurvivalGame/Estate/Weather:
  MPC_EstateWeather   Rain, Overcast, Daylight and Shelter0-7 (x, y, radius, top z cm of the roofs
                      nearest the camera), set every frame by UHomesteadWeather
  SM_RainStreaks      NEAR + FAR small quads; M_Rain lays each out as a falling streak
  M_Rain, MI_Rain     translucent unlit streaks in a world-anchored lattice wrapped round the camera
  M_RainClouds, MI_RainClouds   the overcast cloud layer, drawn only over sky pixels
and imports /Game/SurvivalGame/Audio/Ambience/RainLoop.

SM_RainStreaks packs each streak's layer and rank into UV0.x (OBJ has one UV set): UV0.x = corner
(0 or 1) + 2 * (layer * 1000 + rank bucket), UV0.y = along the streak. Every quad is a 1 cm square
at its streak's home position in the layer's box, so the importer keeps it (no degenerate triangles).
"""
import os
import random

import unreal

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
FOLDER = "/Game/SurvivalGame/Estate/Weather"
LIB = unreal.EditorAssetLibrary
MEL = unreal.MaterialEditingLibrary
TOOLS = unreal.AssetToolsHelpers.get_asset_tools()
SMS = unreal.get_editor_subsystem(unreal.StaticMeshEditorSubsystem)
NOISE = "/Game/SurvivalGame/Estate/Ground/T_GrassWind"

# Streak layers: count and box size (cm). The near box is dense and sharp; the far box fills the
# middle distance with fewer, fainter streaks.
NEAR = (16000, (2000.0, 2000.0, 1400.0))
FAR = (9000, (6000.0, 6000.0, 2400.0))
SHELTERS = 8


def streak_obj(path):
    rng = random.Random(1851)
    lines = ["# Rain streak quads, generated by Scripts/Terrain/build_weather.py"]
    uvs, faces = [], []
    index = 1
    for layer, (count, box) in enumerate((NEAR, FAR)):
        for _ in range(count):
            cx, cy, cz = (rng.uniform(-b / 2, b / 2) for b in box)
            code = 2 * (layer * 1000 + rng.randrange(1000))
            for u, v in ((0, 0), (1, 0), (1, 1), (0, 1)):
                lines.append(f"v {cx + u - 0.5:.2f} {-cy:.2f} {cz + v:.2f}")
                uvs.append(f"vt {code + u} {v}")
            faces.append(f"f {index}/{index} {index + 2}/{index + 2} {index + 1}/{index + 1}")
            faces.append(f"f {index}/{index} {index + 3}/{index + 3} {index + 2}/{index + 2}")
            index += 4
    with open(path, "w") as f:
        f.write("\n".join(lines + uvs + faces) + "\n")


def import_file(source, destination, name):
    task = unreal.AssetImportTask()
    task.set_editor_property("filename", source)
    task.set_editor_property("destination_path", destination)
    task.set_editor_property("destination_name", name)
    task.set_editor_property("automated", True)
    task.set_editor_property("replace_existing", True)
    task.set_editor_property("save", False)
    TOOLS.import_asset_tasks([task])
    asset = unreal.load_asset(f"{destination}/{name}")
    if not asset:
        raise RuntimeError(f"Could not import {source}")
    return asset


def build_mesh():
    out = os.path.join(REPO, "Saved", "Weather")
    os.makedirs(out, exist_ok=True)
    path = os.path.join(out, "SM_RainStreaks.obj")
    streak_obj(path)
    mesh = import_file(path, FOLDER, "SM_RainStreaks")
    settings = SMS.get_lod_build_settings(mesh, 0)
    settings.set_editor_property("generate_lightmap_u_vs", False)
    settings.set_editor_property("recompute_normals", True)
    settings.set_editor_property("recompute_tangents", True)
    settings.set_editor_property("remove_degenerates", False)
    settings.set_editor_property("use_full_precision_u_vs", True)
    settings.set_editor_property("distance_field_resolution_scale", 0.0)
    SMS.set_lod_build_settings(mesh, 0, settings)
    nanite = mesh.get_editor_property("nanite_settings")
    nanite.set_editor_property("enabled", False)
    mesh.set_editor_property("nanite_settings", nanite)
    SMS.remove_collisions(mesh)
    LIB.save_loaded_asset(mesh, False)
    return mesh


def build_mpc():
    path = f"{FOLDER}/MPC_EstateWeather"
    mpc = unreal.load_asset(path) if LIB.does_asset_exist(path) else None
    if mpc is None:
        mpc = TOOLS.create_asset("MPC_EstateWeather", FOLDER, unreal.MaterialParameterCollection,
                                 unreal.MaterialParameterCollectionFactoryNew())
    scalars = []
    for name, value in (("Rain", 0.0), ("Overcast", 0.0), ("Daylight", 1.0)):
        s = unreal.CollectionScalarParameter()
        s.set_editor_property("parameter_name", name)
        s.set_editor_property("default_value", value)
        scalars.append(s)
    vectors = []
    for i in range(SHELTERS):
        v = unreal.CollectionVectorParameter()
        v.set_editor_property("parameter_name", f"Shelter{i}")
        v.set_editor_property("default_value", unreal.LinearColor(0, 0, 0, -1.0e7))
        vectors.append(v)
    mpc.set_editor_property("scalar_parameters", scalars)
    mpc.set_editor_property("vector_parameters", vectors)
    LIB.save_loaded_asset(mpc, False)
    return mpc


RAIN_VERTEX = """
float rest = floor(UV.x * 0.5);
float u = UV.x - 2.0 * rest;
float layer = floor(rest / 1000.0);
float rank = (rest - layer * 1000.0 + 0.5) / 1000.0;
float3 box = layer < 0.5 ? Box.xyz : FarBox.xyz;
float3 centre = LocalPos - float3(u - 0.5, 0.0, UV.y);
float speed = lerp(Motion.x, Motion.y, frac(rank * 37.7));
float wa = radians(Motion.w);
float gust = 0.7 + 0.3 * sin(Time * 0.6 + rank * 6.2831853);
float3 vel = float3(cos(wa) * Motion.z * gust, sin(wa) * Motion.z * gust, -speed);
float3 p = centre + vel * Time;
float3 rel = (frac((p - Cam) / box + 0.5) - 0.5) * box;
rel.z += box.z * 0.2;
float3 pos = Cam + rel;
float keep = step(rank, RainNow * (layer < 0.5 ? 1.0 : 0.85));
float4 roofs[8] = {S0, S1, S2, S3, S4, S5, S6, S7};
[unroll] for (int i = 0; i < 8; i++)
    if (pos.z < roofs[i].w && length(pos.xy - roofs[i].xy) < roofs[i].z) keep = 0.0;
float3 dir = normalize(vel);
float3 toCam = Cam - pos;
float dist = max(length(toCam), 1.0);
float3 right = normalize(cross(dir, toCam / dist));
float width = max(Look.y, dist * Look.z);
float len = Look.x * speed / 800.0;
float fade = Look.y / width * smoothstep(Look.w, Look.w * 2.5, dist)
    * (1.0 - smoothstep(box.x * 0.36, box.x * 0.5, length(rel.xy)));
float3 corner = keep > 0.5 ? pos + right * (u - 0.5) * width + dir * (UV.y - 0.5) * len : pos;
Interp = float4(fade * keep, u, UV.y, rank);
return corner - WP;
"""

RAIN_PIXEL = """
float across = 1.0 - pow(abs(I.y * 2.0 - 1.0), 2.0);
float along = sin(3.14159265 * saturate(I.z));
Alpha = saturate(Opacity * I.x * across * along * (0.7 + 0.6 * frac(I.w * 53.1)));
return Colour.rgb * lerp(0.12, 1.0, saturate(Day));
"""

CLOUD_PIXEL = """
float3 d = -normalize(V);
float up = d.z;
float wa = radians(Cloud.w);
float2 drift = float2(cos(wa), sin(wa)) * Time * Cloud.y;
float2 uv = d.xy / max(up, 0.035) * Cloud.x;
float n1 = Texture2DSample(Noise, NoiseSampler, uv + drift).r;
float n2 = Texture2DSample(Noise, NoiseSampler, uv * 2.7 + 0.37 + drift * 1.6).r;
float n = n1 * 0.65 + n2 * 0.35;
float o = saturate(Oc);
float edge = 1.05 - o * 1.1;
float cover = smoothstep(edge, edge + 0.3, n);
cover = max(cover, o * smoothstep(0.3, 0.0, up));
float sky = step(Cloud.z, Depth);
Alpha = saturate(cover * o) * sky;
float shade = lerp(1.05, 0.72, saturate(n * 1.2 - 0.1));
return Colour.rgb * shade * lerp(0.07, 1.0, saturate(Day));
"""


def material(name, blend, two_sided=True):
    path = f"{FOLDER}/{name}"
    m = unreal.load_asset(path) if LIB.does_asset_exist(path) else None
    if m is None:
        m = TOOLS.create_asset(name, FOLDER, unreal.Material, unreal.MaterialFactoryNew())
    for _ in range(8):
        if MEL.get_num_material_expressions(m) == 0:
            break
        MEL.delete_all_material_expressions(m)
    m.set_editor_property("blend_mode", blend)
    m.set_editor_property("shading_model", unreal.MaterialShadingModel.MSM_UNLIT)
    m.set_editor_property("two_sided", two_sided)
    return m


class Graph:
    def __init__(self, m):
        self.m = m

    def node(self, cls, x, y, **props):
        e = MEL.create_material_expression(self.m, cls, x, y)
        for k, v in props.items():
            e.set_editor_property(k, v)
        return e

    def link(self, a, out, b, pin=""):
        if not MEL.connect_material_expressions(a, out, b, pin):
            raise RuntimeError(f"Could not wire {a.get_name()}.{out} -> {b.get_name()}.{pin}")

    def vector(self, name, value, x, y):
        return self.node(unreal.MaterialExpressionVectorParameter, x, y, parameter_name=name,
                         default_value=unreal.LinearColor(*value), group="Weather")

    def scalar(self, name, value, x, y):
        return self.node(unreal.MaterialExpressionScalarParameter, x, y, parameter_name=name, default_value=value, group="Weather")

    def mpc(self, collection, name, x, y):
        return self.node(unreal.MaterialExpressionCollectionParameter, x, y, collection=collection, parameter_name=name)

    def custom(self, code, inputs, x, y, extra=(), kind=unreal.CustomMaterialOutputType.CMOT_FLOAT3):
        c = self.node(unreal.MaterialExpressionCustom, x, y, code=code, output_type=kind, description="EstateWeather")
        ins = []
        for n, _ in inputs:
            ci = unreal.CustomInput()
            ci.set_editor_property("input_name", n)
            ins.append(ci)
        c.set_editor_property("inputs", ins)
        outs = []
        for n, k in extra:
            o = unreal.CustomOutput()
            o.set_editor_property("output_name", n)
            o.set_editor_property("output_type", k)
            outs.append(o)
        c.set_editor_property("additional_outputs", outs)
        for n, (src, out) in inputs:
            self.link(src, out, c, n)
        return c

    def screen_constant(self, colour, x, y):
        """colour shown at the same screen brightness whatever the eye adaptation (exposure)."""
        cls = getattr(unreal, "MaterialExpressionEyeAdaptationInverse", None)
        if cls is not None:
            e = self.node(cls, x, y)
            self.link(colour, "", e, "")
            return e
        eye = self.node(unreal.MaterialExpressionEyeAdaptation, x, y + 80)
        div = self.node(unreal.MaterialExpressionDivide, x, y)
        self.link(colour, "", div, "A")
        self.link(eye, "", div, "B")
        return div


def build_rain(mpc):
    m = material("M_Rain", unreal.BlendMode.BLEND_TRANSLUCENT)
    m.set_editor_property("used_with_static_lighting", False)
    g = Graph(m)
    F1, F4 = unreal.CustomMaterialOutputType.CMOT_FLOAT1, unreal.CustomMaterialOutputType.CMOT_FLOAT4
    wp = g.node(unreal.MaterialExpressionWorldPosition, -1600, -600)
    wp.set_editor_property("world_position_shader_offset", unreal.WorldPositionIncludedOffsets.WPT_EXCLUDE_ALL_SHADER_OFFSETS)
    local = g.node(unreal.MaterialExpressionTransformPosition, -1400, -500)
    local.set_editor_property("transform_source_type", unreal.MaterialPositionTransformSource.TRANSFORMPOSSOURCE_WORLD)
    local.set_editor_property("transform_type", unreal.MaterialPositionTransformSource.TRANSFORMPOSSOURCE_LOCAL)
    g.link(wp, "", local, "")
    uv = g.node(unreal.MaterialExpressionTextureCoordinate, -1600, -400, coordinate_index=0)
    cam = g.node(unreal.MaterialExpressionCameraPositionWS, -1600, -300)
    time = g.node(unreal.MaterialExpressionTime, -1600, -200)
    rain = g.mpc(mpc, "Rain", -1600, -100)
    roofs = [g.mpc(mpc, f"Shelter{i}", -1600, 0 + 60 * i) for i in range(SHELTERS)]
    box = g.vector("Box", (*NEAR[1], 0), -1400, 500)
    far = g.vector("FarBox", (*FAR[1], 0), -1400, 580)
    motion = g.vector("Motion", (550.0, 850.0, 220.0, 30.0), -1400, 660)     # fall cm/s min, max, wind cm/s, heading deg
    look = g.vector("Look", (75.0, 0.8, 0.0012, 60.0), -1400, 740)        # length cm at 8 m/s, width cm, width per cm of distance, near fade cm
    inputs = [("LocalPos", (local, "")), ("UV", (uv, "")), ("Cam", (cam, "")), ("Time", (time, "")), ("RainNow", (rain, "")),
              ("WP", (wp, "")), ("Box", (box, "RGB")), ("FarBox", (far, "RGB")), ("Motion", (motion, "RGBA")), ("Look", (look, "RGBA"))]
    inputs += [(f"S{i}", (r, "")) for i, r in enumerate(roofs)]
    vs = g.custom(RAIN_VERTEX, inputs, -900, -200, extra=(("Interp", F4),))
    interp = g.node(unreal.MaterialExpressionVertexInterpolator, -600, 200)
    g.link(vs, "Interp", interp, "VS")
    day = g.mpc(mpc, "Daylight", -600, 350)
    colour = g.vector("Colour", (0.72, 0.76, 0.8, 0), -600, 420)
    opacity = g.scalar("Opacity", 0.7, -600, 500)
    ps = g.custom(RAIN_PIXEL, [("I", (interp, "PS")), ("Day", (day, "")), ("Colour", (colour, "RGB")), ("Opacity", (opacity, ""))],
                  -300, 300, extra=(("Alpha", F1),))
    emissive = g.screen_constant(ps, -50, 300)
    P = unreal.MaterialProperty
    for src, out, prop in ((emissive, "", P.MP_EMISSIVE_COLOR), (ps, "Alpha", P.MP_OPACITY), (vs, "", P.MP_WORLD_POSITION_OFFSET)):
        if not MEL.connect_material_property(src, out, prop):
            raise RuntimeError(f"M_Rain: could not connect {prop}")
    MEL.recompile_material(m)
    LIB.save_loaded_asset(m, False)
    return m


def build_clouds(mpc):
    m = material("M_RainClouds", unreal.BlendMode.BLEND_TRANSLUCENT)
    g = Graph(m)
    F1 = unreal.CustomMaterialOutputType.CMOT_FLOAT1
    view = g.node(unreal.MaterialExpressionCameraVectorWS, -1200, -200)
    time = g.node(unreal.MaterialExpressionTime, -1200, -100)
    depth = g.node(unreal.MaterialExpressionSceneDepth, -1200, 0)
    noise = g.node(unreal.MaterialExpressionTextureObjectParameter, -1200, 100, parameter_name="CloudNoise",
                   texture=unreal.load_asset(NOISE), sampler_type=unreal.MaterialSamplerType.SAMPLERTYPE_LINEAR_GRAYSCALE)
    oc = g.mpc(mpc, "Overcast", -1200, 200)
    day = g.mpc(mpc, "Daylight", -1200, 260)
    cloud = g.vector("Cloud", (0.35, 0.004, 1.0e7, 30.0, ), -1200, 340)   # scale, drift per s, sky depth cm, heading deg
    colour = g.vector("CloudColour", (0.58, 0.6, 0.63, 0), -1200, 420)
    ps = g.custom(CLOUD_PIXEL, [("V", (view, "")), ("Time", (time, "")), ("Depth", (depth, "")), ("Noise", (noise, "")),
                                ("Oc", (oc, "")), ("Day", (day, "")), ("Cloud", (cloud, "RGBA")), ("Colour", (colour, "RGB"))],
                  -700, 0, extra=(("Alpha", F1),))
    emissive = g.screen_constant(ps, -400, 0)
    P = unreal.MaterialProperty
    for src, out, prop in ((emissive, "", P.MP_EMISSIVE_COLOR), (ps, "Alpha", P.MP_OPACITY)):
        if not MEL.connect_material_property(src, out, prop):
            raise RuntimeError(f"M_RainClouds: could not connect {prop}")
    MEL.recompile_material(m)
    LIB.save_loaded_asset(m, False)
    return m


def instance(parent, name):
    path = f"{FOLDER}/{name}"
    mi = unreal.load_asset(path) if LIB.does_asset_exist(path) else None
    if mi is None:
        mi = TOOLS.create_asset(name, FOLDER, unreal.MaterialInstanceConstant, unreal.MaterialInstanceConstantFactoryNew())
    MEL.set_material_instance_parent(mi, parent)
    LIB.save_loaded_asset(mi, False)
    return mi


def import_sound():
    wav = os.path.join(REPO, "Assets", "Audio", "Ambience", "RainLoop.wav")
    if not os.path.exists(wav):
        print("RainLoop.wav missing: run python Scripts/prepare_rain_loop.py")
        return None
    sound = import_file(wav, "/Game/SurvivalGame/Audio/Ambience", "RainLoop")
    sound.set_editor_property("looping", True)
    LIB.save_loaded_asset(sound, False)
    return sound


def main():
    mpc = build_mpc()
    mesh = build_mesh()
    rain = build_rain(mpc)
    clouds = build_clouds(mpc)
    mi_rain = instance(rain, "MI_Rain")
    instance(clouds, "MI_RainClouds")
    mesh.set_material(0, mi_rain)
    LIB.save_loaded_asset(mesh, False)
    import_sound()
    for m in (rain, clouds):
        s = MEL.get_statistics(m)
        print(m.get_name(), "instructions: vs", s.num_vertex_shader_instructions, "ps", s.num_pixel_shader_instructions)
    print("weather built:", SMS.get_number_verts(mesh, 0), "streak verts")


if __name__ == "__main__":
    main()
