"""Generate the runtime public road: the manor-to-town road's centreline in world centimetres with its
chainage, the safe travel endpoints and sign anchors, and the bridge keep-out.

    python Scripts\\Terrain\\public_road.py
        -> Source/SurvivalGame/Simulation/HomesteadEstatePublicRoad.inc

Reads Scripts/Terrain/estate_layout.json ("road", "roadProfile", "river", "riverSurface") and the heightfield
(for sign heights). The road's chainage (metres along it from the manor forecourt) is the one the
travel, sign and roadside-forage lanes quote, so the points are the layout's own 4 m samples, unchanged.
"""
import json
import math
import os

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.normpath(os.path.join(HERE, "..", ".."))
LAYOUT = os.path.join(HERE, "estate_layout.json")
R16 = os.path.join(REPO, "Content", "SurvivalGame", "Estate", "Runtime", "EstateHeightfield.r16")
OUT = os.path.join(REPO, "Source", "SurvivalGame", "Simulation", "HomesteadEstatePublicRoad.inc")
SIZE, H = 4033, 2016

SIGN_OFFSET_M = 4.2            # a sign stands this far off the centreline, on the verge
BRIDGE_HALF_ALONG_M = 20.0     # the bridge keep-out: deck and ramps (chainage 664-704 about the crossing)
BRIDGE_HALF_ACROSS_M = 6.0
# The signs: (name, chainage m or None for the gateway, side (+1 = right of travel toward town), facing).
# "toTown" signs face walkers coming from the manor; "toManor" faces those leaving town.
GATEWAY = (-55.0, 90.0)


def main():
    layout = json.load(open(LAYOUT))
    road = np.asarray(layout["road"], np.float64)
    prof = np.asarray(layout["roadProfile"], np.float64)
    seg = np.hypot(*np.diff(road, axis=0).T)
    chain = np.r_[0.0, np.cumsum(seg)]
    z = (np.fromfile(R16, "<u2").reshape(SIZE, SIZE).astype(np.float64) - 32768.0) / 128.0

    def ground(x, y):
        return float(z[int(round(y)) + H, int(round(x)) + H])

    def frame(ch):
        k = int(np.clip(np.searchsorted(chain, ch), 1, len(road) - 2))
        d = road[k + 1] - road[k - 1]
        d /= np.linalg.norm(d)
        t = (ch - chain[k - 1]) / max(chain[k] - chain[k - 1], 1e-9)
        p = road[k - 1] + (road[k] - road[k - 1]) * min(max(t, 0.0), 1.0)
        return p, d

    # The river crossing: the road point nearest the river's graded course.
    river = np.asarray(layout["river"][:layout.get("riverEnd", len(layout["river"]))], np.float64)
    d2 = ((road[:, None, :] - river[None, :, :]) ** 2).sum(-1)
    k, j = np.unravel_index(np.argmin(d2), d2.shape)
    bridge_ch = float(chain[k])
    gate_ch = float(chain[int(np.argmin(np.hypot(*(road - np.array(GATEWAY)).T)))])

    signs = []
    for name, ch, side, toward in (("ManorRoadSign", 12.0, -1, "town"),
                                   ("GatewayRoadSign", gate_ch + 14.0, -1, "town"),
                                   ("TownRoadSign", float(chain[-1]) - 14.0, 1, "manor")):
        p, d = frame(ch)
        right = np.array([-d[1], d[0]])       # x north, y east: right of the heading (Unreal is left-handed)
        q = p + right * side * SIGN_OFFSET_M
        heading = math.degrees(math.atan2(d[1], d[0]))
        yaw = heading if toward == "town" else heading + 180.0
        signs.append((name, ch, q, ground(*q), (yaw + 360.0) % 360.0))

    lines = [
        "// Generated by Scripts/Terrain/public_road.py from estate_layout.json; do not edit by hand.",
        f"// The public road from the manor forecourt to town: {len(road)} centreline points (cm), {chain[-1]:.1f} m.",
        "// road(x, y, groundZ, chainage m)",
    ]
    for (x, y), gz, ch in zip(road, prof, chain):
        lines.append(f"road({x * 100.0:.1f}, {y * 100.0:.1f}, {gz * 100.0:.1f}, {ch:.2f});")
    lines.append("// bridge(chainage m, half length m along the road, half width m across it): no placements here")
    lines.append(f"bridge({bridge_ch:.2f}, {BRIDGE_HALF_ALONG_M:.1f}, {BRIDGE_HALF_ACROSS_M:.1f});")
    lines.append("// stop(name, chainage m): travel endpoints on the walkable road bed")
    lines.append(f"stop(\"Manor\", {12.0:.2f});")
    lines.append(f"stop(\"Gateway\", {gate_ch:.2f});")
    lines.append(f"stop(\"Town\", {float(chain[-1]) - 6.0:.2f});")
    lines.append("// sign(name, chainage m, x cm, y cm, ground z cm, yaw deg): the face points along yaw")
    for name, ch, q, gz, yaw in signs:
        lines.append(f"sign(\"{name}\", {ch:.2f}, {q[0] * 100.0:.1f}, {q[1] * 100.0:.1f}, {gz * 100.0:.1f}, {yaw:.1f});")
    with open(OUT, "w", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"public road: {len(road)} points, {chain[-1]:.1f} m; bridge at {bridge_ch:.1f} m; gateway {gate_ch:.1f} m -> {OUT}")


if __name__ == "__main__":
    main()
